### ISSUE TITLE
Add compatability with the 'Inventory Tabs (Updated)' mod

### ISSUE THREAD

**Issue by mateowoetam** [TeamMidnightDust/MidnightControls#100]
**Is your feature request related to a problem? Please describe.**
I would like for there to be added support with this mod, this mod adds the ability to access inventory blocks as tabs from your main inventory. 

**Describe the solution you'd like**
I would like the MidnightControll mods to add support to use the bumper/'Hotbar left & right' controls to switch between them just like in the creative inventory.

**Describe alternatives you've considered**
I'm not sure what alternative there is other than to get used to not being able to do that with this mod.

**Additional context**
the mod's GitHub page is: https://github.com/Andrew6rant/inventorytabs
this is an example of how it looks:
![2022-09-05_11 36 33](https://user-images.githubusercontent.com/79337611/188483289-6fdcf7e1-d115-4bb7-aff2-63216ffa7db9.png)

**Comment by Motschen** [comment]
Will be a feature of MidnightControls 1.6.0 which is going to release in the coming week
