### ISSUE TITLE
Implement a customizable action bind radial menu

### ISSUE THREAD

**Issue by autione** [TeamMidnightDust/MidnightControls#101]
**Is your feature request related to a problem? Please describe.**
This could help players that like to play with controllers on bigger modpacks, letting them use the radial menu as described below.

**Describe the solution you'd like**
Adding a radial menu that opens up when you hold a button. It would serve for binding additional actions, such as opening backpacks or doing gestures (in mods that let you do so), that could be selected with an analog stick.

It could have 6 or 8 buttons for binding controls, that would execute its action after releasing the radial menu button, and a close button in the middle or at the bottom for cancelling running any actions.

**Describe alternatives you've considered**
None for Fabric. Although, the Controllable mod by MrCrayfish on Forge has a similar feature, which, as said, lets you bind game controls to buttons in the menu.

**Additional context**
None.

**Comment by Motschen** [comment]
The next version will contain a radial menu that lists all unbound keys, in a future version I'll implement a fully customizable one
