### ISSUE TITLE
Allow toggle support for sprint and sneak buttons on the gamepad but not for the keyboard

### ISSUE THREAD

**Issue by ShygalCoco** [TeamMidnightDust/MidnightControls#102]
**Is your feature request related to a problem? Please describe.**
It's quite inconvenient that you can't set it so that sprint and sneak is a toggle button instead of requiring to hold them when using a gamepad. I understand that you can change that with the game accessibility options but that change will apply to both the keyboard and the gamepad when I'd only want the toggle option for the gamepad.

**Describe the solution you'd like**
Add a setting in the gamepad options menu that allows you to make the sprint and sneak buttons togglable for the gamepad but not for the keyboard.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by slushieuwu** [comment]
Yes please, it’s pretty annoying having to switch it in accessibility settings even though it switches seamlessly between controller and kb+m
