### ISSUE TITLE
a special error in inventory HUD

### ISSUE THREAD

**Issue by Kongtu5i** [TeamMidnightDust/MidnightControls#104]
i turn off the HUD, but it is still show in the inventory HUD，i think it have some incomprehensible errors
![QQ截图20220919174753](https://user-images.githubusercontent.com/101731748/190992930-4e0f06c4-0051-48f7-b3ba-bfd92185caf3.jpg)
![QQ截图20220919174803](https://user-images.githubusercontent.com/101731748/190992950-0b7ab97e-e5ad-4458-afd2-5fbe95828fba.jpg)
![QQ截图20220919174810](https://user-images.githubusercontent.com/101731748/190992959-5a1d017e-07de-4748-951c-f010344667de.jpg)

**Comment by Kongtu5i** [comment]
if you need more infomation about it ,i can record a video

**Comment by Motschen** [comment]
Will be fixed in the next version
