### ISSUE TITLE
The new UI layout behaviour found in MidnightControls 1.6.0 that was meant to address issue #95 ends up often resulting in severe clipping into the chat overlay at many common resolutions (including 1920x1080).

### ISSUE THREAD

**Issue by akemin-dayo** [TeamMidnightDust/MidnightControls#106]
## Description
The changes that were made to MidnightControls's UI layout behaviour in order to address issue #95 actually ends up often causing severe clipping into the chat overlay at many common resolutions (including 1920x1080).

As a result, I think it would be a good idea to add a configuration option to MidnightControls that restores the old layout behaviour, as interfering with the chat overlay is quite unusable.

## Current workarounds
* **Downgrade to MidnightControls 1.5.0.**
* Isolate and revert the relevant changes in the code, then build your own patched copy of 1.6.0.

## Screenshots
MidnightControls 1.6.0 (new, post-#95 behaviour, 3456x2160)
![image](https://user-images.githubusercontent.com/1980487/191633563-247b7027-6e82-4ffc-928a-c0ebffa1c066.png)

MidnightControls 1.5.0 (old, pre-#95 behaviour, 3456x2160)
![image](https://user-images.githubusercontent.com/1980487/191632947-8acb0a5b-6cbb-4bf6-aa44-1db1494a51f7.png)

## Reproduction steps
Run Minecraft at a resolution of 1920x1080@4x, or resize your Minecraft window until you see what is happening in the above screenshots.

## Testing environment
* **Resolutions:** 3456x2160@8x (macOS), 1920x1080@4x (Windows)
* **MidnightControls version:** 1.6.0
* **Minecraft versions:** Minecraft 1.19.2 and 1.19
* **Mod loaders:** quilt-loader, fabric-loader
* Occurs with no other mods enabled, as it is purely a MidnightControls UI layout issue.

**Comment by Motschen** [comment]
Well, that's quite an unfortunate situation, either it interferes with the chat menu or with the hotbar.
I'll look into providing a better solution.

**Comment by Motschen** [comment]
This is the best solution I can think of, just putting it on the right side at low resolutions/high gui scales.
![2022-09-23_17 01 56](https://user-images.githubusercontent.com/49783724/191991570-998bbb2f-1d09-4e4e-9038-ca6ac2051d32.png)

**Comment by akemin-dayo** [comment]
That looks like it'll interfere with the Subtitles option (enable them in Accessibility) — have you checked?

**Comment by Motschen** [comment]
Yes, it does, unfortunately.
I honestly feel like I'm out of options here.
Do you think I should just hide the Swap Hands button in that case?

**Comment by akemin-dayo** [comment]
Hmn, ideally the button prompts shouldn't be hidden — would it be feasible to say, restore the old behaviour and then shorten some of the strings only when the UI is too constrained?

**Comment by Motschen** [comment]
I don't think that would be viable, as the strings can't really be shortened any further.
The swap hands button is not really important anyway imo, and only a small fraction of the player-base has such an exotic settings combination anyway, so I'll just hide it.

**Comment by akemin-dayo** [comment]
Mnn, that's fair. Will you consider adding an option to always show all buttons even if they'll interfere with the UI? (Basically, the 1.5.0 behaviour — at my resolutions (1920x1080@4x, 3456x2160@8x), it doesn't intersect with the inventory bar so it's fine for me and many others.)

**Comment by Motschen** [comment]
Okay, then I'll just lower the scaled width at which the window is considered too crammed.
