### ISSUE TITLE
Allow for easy switching between controller profiles

### ISSUE THREAD

**Issue by bendavis78** [TeamMidnightDust/MidnightControls#107]
On my Steam Deck, I'd like to be able to easily switch between my docked config (which uses an Xbox controller) and my undocked steam Deck config. 

Right now I don't see a way to easily switch between mappings.

**Comment by Motschen** [comment]
Good idea, I'll look into it.

**Comment by Motschen** [comment]
I managed to implement this functionality for button bindings in the first development build of 1.6.1:
[midnightcontrols-1.6.1-dev+1.19.zip](https://github.com/TeamMidnightDust/MidnightControls/files/9636486/midnightcontrols-1.6.1-dev%2B1.19.zip)

Please test the jar from the zip (or build the latest commit yourself) and provide me with some feedback on it.
The option can be found in the Controller Options tab.
