### ISSUE TITLE
Touchscreen mode

### ISSUE THREAD

**Issue by arr512** [TeamMidnightDust/MidnightControls#109]
Hello. I have just tested the touchscreen mode on my windows tablet. It doesn't work. Are you going to refine the touchscreen mode?

**Comment by Motschen** [comment]
I'd like to, but I can't, since I don't own a tablet myself and there seems to be some limitations related to multitouch.
I've reopened issue #20, so I'll close this one.

**Comment by Felix14-v2** [comment]
> I don't own a tablet myself

What about PojavLauncher/HMCL-PE, by the way?
