### ISSUE TITLE
Front block placing only places ghost blocks

### ISSUE THREAD

**Issue by Gecked-Deck** [TeamMidnightDust/MidnightControls#11]
**Describe the bug**
When using front block placing, it places ghose blocks

**To Reproduce**
Use front block placing, I was on a single player world.

**Expected behavior**
To place blocks regularly.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: SteamOS 3.0
 - Minecraft 1.18.2
 - Fabric 0.14.4
 - Mods Iris v1.2.4-build.38, Mod Menu v3.2.1, Sodium v0.4.1+build.15
 - Version 0.1.0
 - Branch Stable

**Additional context**
This is on Steam Deck running under gamescope. Works amazingly btw :)

**Comment by Motschen** [comment]
Will look into this, thanks for reporting :)
Btw, could you please verify that the back pedals also work as expected?
I wasn't able to test them, since I don't own a Steam Deck yet as I'm in the After Q3 section, so I had to do some guesswork

**Comment by Motschen** [comment]
I looked into the front placing issue and it doesn't happen to me, but I pushed an update to refresh the state of Front Block Placing, Fast Block Placing and Vertical Reacharound on config change, you could try if this fixes it.

**Comment by Gecked-Deck** [comment]
The back paddles don't work unless you bind them to a key and then bind that in MC or bind it to another controller button. Unless this mod supports steam input API which would be pretty hard to do, I don't think it'd be possible.

**Comment by Motschen** [comment]
You might also want to contribute the Steam Deck mappings to the official repository:
https://github.com/gabomdq/SDL_GameControllerDB
Then, Steam Deck users don't have to download the gamepad tool and copy the mappings themselves.

**Comment by Motschen** [comment]
Fixed in the latest version!
