### ISSUE TITLE
Switch Pro Controller moving cursor without me touching controls

### ISSUE THREAD

**Issue by BurpOfFury** [TeamMidnightDust/MidnightControls#111]
When I try using my Nintendo Switch Pro Controller with the mod, the controller navigates the main menu on its own without me doing anything. If I open the settings with my mouse, the controller closes it again. It sometimes even closes the game. It does this every time I plug in the controller. I have tried the mod on two different computers and had the same issue on both of them. I know my controller doesn't have stick drift because I can use it on my Switch and with Steam games without any problems.

**Comment by Motschen** [comment]
Try increasing the dead zone values in MidnightControls' settings

**Comment by plyfrm** [comment]
I am also experiencing this, not just cursor movements but all controls seem to be behaving erratically both in game and in menus. Changing deadzone values results in the exact same behaviour.

**Comment by 1unar-Eclipse** [comment]
Can attest to retroposon; deadzones did nothing to fix the spontaneous movement - if I have to guess, it may have to do with gyro implementation or DirectInput being weird, since Windows's controller input viewer has a similar issue

**Comment by Motschen** [comment]
Nintendo Switch Pro Controller-related issues are now handled in #10
