### ISSUE TITLE
Bug: Buggy keybinds

### ISSUE THREAD

**Issue by aloshTM** [TeamMidnightDust/MidnightControls#112]
**Describe the bug**
Keybind set to some glitched keybind that does nothing

**To Reproduce**
1. Use CurseForge, PolyMC, just someplace you can get the modpack on linux
2. Open the modpack and connect a generic controller
3. Go to Midnight's options, then go to "Controller Bindings"
4. **Click** on any keybind

**Expected behavior**
I should be able to change the keybind like normal
**Screenshots**
![image](https://user-images.githubusercontent.com/74996153/194182895-592a4857-826f-4488-b977-65a2a9b28674.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Minecraft 1.19.2
 - Fabric build 0.14.9
 - Mods/Modpack: [Fabulously Optimized](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized)
 - Version: 1.6.0+1.19
 - Branch: main

**Additional context**

**Comment by Motschen** [comment]
Which controller are you using? Does it also happen with other controllers? Also, which distro are you running?

**Comment by aloshTM** [comment]
I am using [Nobara Official (GNOME)](nobaraproject.org)
It also happens with any controller I tested (xbox, joycons, dualshock)

**Comment by Motschen** [comment]
Can you use the controller in-game to move the cursor and interact with the world?

**Comment by aloshTM** [comment]
No, it seems to do nothing

**Comment by Motschen** [comment]
Very strange... doesn't happen for me on Garuda and Fedora.
Can you test if your controllers work properly in https://generalarcade.com/gamepadtool/ ?

**Comment by Motschen** [comment]
Does this still occur on the latest versions?

**Comment by aloshTM** [comment]
i forgot
