### ISSUE TITLE
How to use with steam controller

### ISSUE THREAD

**Issue by al-en1** [TeamMidnightDust/MidnightControls#115]
Ive tried opening up SDL2 gamepad tool but it gives me this error. I have tried reinstalling the program
![Capture](https://user-images.githubusercontent.com/110346251/196011733-4f3d85bf-bd3a-49a8-a747-5a7ef415cf2e.PNG)

**Comment by Motschen** [comment]
You need to install Visual C++ Redistributables first for the gamepad tool to work.
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
Here is the latest one: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by al-en1** [comment]
I have done that with the included setup file, but it cannot detect my controller, done it with and without steam open, I know this is an issue you cannot fix so could you possibly tell me a solution( if you do know one) or if you can tell me the SDL2 game pad tool github.
