### ISSUE TITLE
Bug: "Toggle Sneak" stops when accessing inventory

### ISSUE THREAD

**Issue by Torchwood12** [TeamMidnightDust/MidnightControls#119]
When I configure sneak option to toggle (using new settings "Toggle sneak on controller"), it will release sneak when accessing inventory. It didn't do that in previous version, when sneak toggle was configured using default Minecraft setting.

**To Reproduce**
1. Enable "Toggle sneak on controller"
2. Sneak
3. Open inventory
4. You will notice that your character stops sneaking

**Expected behavior**
It should keep sneaking even when inventory is opened

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.19.2
 - Fabric 0.64.0
 - Version 1.7.0
 - Branch Stable

**Comment by Motschen** [comment]
Moving this to #132
