### ISSUE TITLE
Feature: Dedicated Dismount Keybind

### ISSUE THREAD

**Issue by vos6434** [TeamMidnightDust/MidnightControls#120]
**Is your feature request related to a problem? Please describe.**
I have shift toggle enabled so whenever I dismount a boat, I keep shifting which makes me sink in water.

**Describe the solution you'd like**
A dedicated dismount keybind would solve the problem entirely.

**Describe alternatives you've considered**
You could just make toggle shift not toggle when on a mount but I think a dedicated keybind would be very useful.

**Comment by Motschen** [comment]
I don't think many people would make use of such a separate keybind.
I'm going to close this and add it to the related issue #132
