### ISSUE TITLE
Chat offset for Steam Deck on-screen keyboard

### ISSUE THREAD

**Issue by applejag** [TeamMidnightDust/MidnightControls#126]
**Is your feature request related to a problem? Please describe.**
When opening the in-game chat and then the on-screen keyboard from Steam Deck, the on-screen keyboard is on top of the chat so I can't see what I'm typing.

**Describe the solution you'd like**
Either to have the keyboard open at the top instead, or make the chat offset from the bottom so it's above the virtual on-screen keyboard when active.

Another option if integration is too difficult: to allow opening the chat but with a configurable offset. And then adding a preset/suggestion of 357 pixels, as that seems to be the height of the Steam Deck virtual keyboard.

Looking at the steamworks4j that you mentioned in a different issue (https://github.com/TeamMidnightDust/MidnightControls/issues/77#issuecomment-1192315269), then it seems to have a method for opening text inputs: https://github.com/code-disaster/steamworks4j/blob/1.9.0/java-wrapper/src/main/java/com/codedisaster/steamworks/SteamUtils.java#L115-L120
Would be useful when specifying the input fields like signs and anvils as well. Found the function on the Steamworks docs as well: https://partner.steamgames.com/doc/api/ISteamUtils#ShowFloatingGamepadTextInput

**Describe alternatives you've considered**
It should allegedly appear from the top when the mouse cursor is at the bottom, but that doesn't work for me in Minecraft (ref: <https://www.reddit.com/r/SteamDeck/comments/uni3tb/comment/i887zx1/?utm_source=reddit&utm_medium=web2x&context=3>). Works like that in Firefox though, where it also seems to be dependent on where the focused input field is and not only where the cursor is.

**Additional context**
Device: Steam Deck
Modpack: Fabulously optimized
Minecraft version: 1.19.2

Screenshot after pressing <kbd>Right D-pad</kbd> to open chat, then <kbd>Steam + X</kbd> to open keyboard (even when having mouse cursor at the bottom):
![image](https://user-images.githubusercontent.com/2477952/199114957-65be1661-81ef-43e5-9ac8-bda645484322.png)

**Comment by Motschen** [comment]
I added an option to move the chat input box to the top of the screen in some update after you reported this :)
