### ISSUE TITLE
The Left Analog stick feels like an 8-way joystick and not fluid

### ISSUE THREAD

**Issue by SmashbrosThe3rd** [TeamMidnightDust/MidnightControls#135]
**Describe the bug**
The Left Analog stick feels strongly restrictive because MidnightControls appears to only emulate WASD.
This inhibits the ability to produce precise movements and makes the controls feel unnatural to use.
This has been tested using an Original Xbox One controller (Computer 1) and the built-in controls of the Steam Deck (Computer 2).
Settings are Default with both setups.

**To Reproduce**
1. Launch Minecraft with MidnightControls enabled.
2. Open any World or connect to any Server.
3. Hold the Left-stick straight up to walk forward.
4. Slowly move the left-stick diagonally towards straight left/right to notice restriction.

**Expected behavior**
Fluid Left-stick movement akin to Legacy Console Edition or Bedrock Edition. Left-stick Axis precision.
The Forge Mod 'Controllable' functions this way and is my expected behavior.

**Screenshots**
Screenshots are unable to provide help with this issue.

**Desktop (please complete the following information):**

Computer 1:
 - OS: Windows 10 22H2
 - Minecraft 1.19.2
 - Fabric 0.14.10
 - Version 1.7.1+1.19
 - Downloaded from Curseforge

Computer 2:
 - OS: SteamOS 3.3.2 build 20221005.1 (Steam Deck)
 - Minecraft 1.18.2
 - Fabric 0.14.10
 - Version 1.5.0+1.18
 - Downloaded from Curseforge

**Additional context**
Just a request: If a fix to this issue does become available, could it please be applied to older Minecraft versions (eg. 1.18.2)?

Thanks in advance.

**Comment by Motschen** [comment]
There were efforts to improve this in MidnightControls 1.7.0 and it works very well with both my DualSense and DualShock controllers, but not on my Xbox One controller.
I've realized that it might be related to me having to change the maximum stick values for that one.
Did you also change the maximum stick values?

**Comment by SmashbrosThe3rd** [comment]
All of the settings are default from a fresh install except for the X & Y axis rotation speeds (40 --> 15) because looking around felt way too fast. No modifications at all regarding the left stick or any other settings.

**Comment by soshimee** [comment]
I can reproduce this too with what I believe is an Xbox Series controller.

**Comment by dogtopus** [comment]
Could be bad deadzone checking. Checking each axis separately instead of the polar vector would cause the movement to be choppy because it could technically block small x axis movements (e.g. (0, 1) -> (-0.1392, 0.9903)) when the stick is in fact fully pushed.

Maybe we should go completely polar in terms of analog stick input?
