### ISSUE TITLE
Add in-game option to use all menus with joystick mouse instead of needing to edit config file

### ISSUE THREAD

**Issue by ShygalCoco** [TeamMidnightDust/MidnightControls#137]
**Is your feature request related to a problem? Please describe.**
I'd wish there'd be a more convenient way to allow for using the joystick mouse to select stuff in all the menus, same for how you control the mouse in the player inventory, instead of having to go out of your way to edit a config file or whatever it was and figure out what text you need to add or remove in order to allow for that.

**Describe the solution you'd like**
There could be a quick option in the controller settings so that you can switch to joystick mouse control, similar to how it's done in the player inventory, for selecting the menu buttons.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Motschen** [comment]
Added in 1.7.2

**Comment by Reyshyram** [comment]
Is it possible to do this in 1.18.2 ? Like putting * in mousScreens in the config file ?

**Comment by Motschen** [comment]
> Is it possible to do this in 1.18.2 ? Like putting * in mousScreens in the config file ?

yes, though you need to put "net.minecraft" into the field instead of the asterisk

**Comment by Reyshyram** [comment]
Waw thanks for the quick answer!
