### ISSUE TITLE
Turning with joystick when on boat is very abrupt?

### ISSUE THREAD

**Issue by philhzss** [TeamMidnightDust/MidnightControls#138]
Hi, on Steam Deck here. Loving this mod, it works really well! I'm just having a small issue and considering Ive seen no reports about it, I'm wondering if something is just wrong on my side?

When using boats, turning is extremely abrupt... It's like if suddenly, my left joystick is mimicking WASD controls. The boat will not turn until I push the joystick almost completely left, and then it starts turning on itself in a circle, until I push the stick completely forward again. 

However, when I'm just walking, the joystick works fine as intented, I can smoothly turn / walk diagonally without issue.

Is this known, or is something wrong on my side? This makes boats extremely hard to control 

Thank you!

**Comment by Motschen** [comment]
Yeah, I've also recently noticed this myself, I'll definitely take a look at it.

**Comment by dogtopus** [comment]
Might be linked to #135?

**Comment by Systoxity** [comment]
Idk if this is a regression or never fixed but seems like boat steering is a bit crazy on MC 26.1.2 with latest midnightcontrols as of this post date.
