### ISSUE TITLE
Using the Mod with a Raphnet Adapter only uses LT and RT and doesn't allow inputs

### ISSUE THREAD

**Issue by MusicDoneDigitally** [TeamMidnightDust/MidnightControls#139]
Basically whenever I try to map a keybind the triggers are called before I even press a button. When using other programs like x360ce and SDL Gamepad tool, I get the same error.

I don't have steps to reproduce this error as it literately happened as soon as I plugged it in.

Steps in a form of a Twitch Clip
[Twitch Clip](https://clips.twitch.tv/OilySolidGaurArgieB8-9nlX54QLDankriuw)

 - OS: Windows 11
 - Minecraft 1.19.2
 - Fabric Not Sure
 - Mods Fabric-API,MidnightControls,Realistic animations,betterFPS
 - Version Not Sure
 - Branch Stable

**Comment by Motschen** [comment]
Try if disabling "triggerFix" in MidnightControls' advanced config fixes your problem.

**Comment by Motschen** [comment]
Gonna close this until I get a reply.
