### ISSUE TITLE
No valid version when trying to download the mod

### ISSUE THREAD

**Issue by MartinSorani** [TeamMidnightDust/MidnightControls#146]
Unable to download and install the mod using third party launchers such as PolyMC or Prism Launcher because the mod does not seem to contain a valid version.

Tested using MC 1.19.2

**To Reproduce**
1. Create a new MC 1.19.x instance in Prism Launcher
2. Edit the instance
3. Go to Mods
4. Click on download mods
5. Select CurseForge as source
6. Enter "MidnightControls" in the search box
7. Filter by 'Any version'
8. Select Midnight Controls from the list

**Expected behavior**
Version selected box should contain a valid version and the Select mod button should be enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/12101366/206930188-bc54eb38-407a-4543-8146-81018fd11e26.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.19.2
 - Forge 43.1.65
 - Mods Fabric API, MidnightLib
 - Branch 1.19.3

**Comment by Motschen** [comment]
MidnightControls is not available for Forge right now, use Controllable instead.
