### ISSUE TITLE
Crash when opening inventory with EMI installed

### ISSUE THREAD

**Issue by Waoweens** [TeamMidnightDust/MidnightControls#151]
**Describe the bug**
When EMI is installed, opening the inventory with a controller connected and enabled will display "Saving world" and then the game will crash.

Log and crash report: https://gist.github.com/Waoweens/81479194d6bc41fad4d00f3b892b6b33

**To Reproduce**
1. Connect a controller
2. Enable controller mode
3. Open a world
4. Open the inventory (with controller or keyboard)
5. Crash

**Expected behavior**
The inventory will open without crashing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux (6.0.12-arch1-1)
 - Minecraft 1.19.2
 - Fabric 
   - Fabric Loader 0.14.2
   - Fabric API 0.69.0+1.19.2
 - Mods
   - EMI 0.5.3+1.19.2
 - Version 1.7.1+1.19
 - Branch ?

**Additional context**

**Comment by Waoweens** [comment]
```
---- Minecraft Crash Report ----
...
java.lang.NoClassDefFoundError: dev/emi/emi/EmiConfig
	at eu.midnightdust.midnightcontrols.client.compat.EMICompat.isEMIEnabled(EMICompat.java:43)
```
https://github.com/TeamMidnightDust/MidnightControls/blob/187844db2ba35bef00790e877b3f7ea2d341a292/src/main/java/eu/midnightdust/midnightcontrols/client/compat/EMICompat.java#L3
https://github.com/TeamMidnightDust/MidnightControls/blob/187844db2ba35bef00790e877b3f7ea2d341a292/src/main/java/eu/midnightdust/midnightcontrols/client/compat/EMICompat.java#L42-L44

"EmiConfig" seems to have been deleted in EMI 0.5.0 (https://github.com/emilyploszaj/emi/commit/b3373c3827772d1912beeab8d10bdd0ebabcdfd1)

Downgrading to EMI 0.4.3 "fixes" the crash

**Comment by Waoweens** [comment]
Nevermind, it has not been deleted, it has been moved to dev/emi/emi/config/EmiConfig

**Comment by Jamalam360** [comment]
Can confirm, same issue

**Comment by Motschen** [comment]
Just backported 1.7.3 to 1.19.2, fixing this crash.
