### ISSUE TITLE
Conflict with Dynamic FPS on latest FAPI

### ISSUE THREAD

**Issue by Madis0** [TeamMidnightDust/MidnightControls#152]
**Describe the bug**
Updating Fabric API from 0.70.0 to 0.71.0 creates this crash on launch.

**To Reproduce**
1. Install Fabulously Optimized 4.6.0-alpha.13 or later
2. Update Fabric API individually

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.19.3
 - Fabric 0.71.0+1.19.3
 - Mods - in the log
 - Version 1.7.2+1.19.3
 - Branch - compiled release from CF

**Additional context**
https://mclo.gs/YcxurS5

Notably Fabric API 0.71.0 is in beta at the moment to test for issues like these, but I figured reporting to you would still make sense.

**Comment by Motschen** [comment]
This is caused only by the new Fabric API update.
I've released 1.7.3 to address this issue, along with some nice new features :)
