### ISSUE TITLE
Why is this marked as "optional" for servers on modrinth?

### ISSUE THREAD

**Issue by pavog** [TeamMidnightDust/MidnightControls#153]
**Describe the bug**
Hi, I would like to know why this mod is marked as optional for servers on modrinth?
https://modrinth.com/mod/midnightcontrols

I don't think that this mod adds any features to the server, right?
So why do I need to install it on my server?

**To Reproduce**
Not really a bug

**Comment by Motschen** [comment]
This is intended, as servers can install this mod to disable some of the features of MidnightControlsExtra.

**Comment by pavog** [comment]
Maybe you can add a note about this to the projects page?
Thank you! :-)
