### ISSUE TITLE
Crash with Fabric API 0.71.0+1.19.3

### ISSUE THREAD

**Issue by mustafakamran98** [TeamMidnightDust/MidnightControls#154]
**Describe the bug**
The game will crash upon starting in 1.19.3 with PrismLauncher 6.1, Fabric Loader 0.14.12, and Fabric API 0.71.0+1.19.3

**To Reproduce**
- Launch with only Fabric API and MidnightControls selected as mods

**Expected behavior**
Game should launch with no problem

**Desktop (please complete the following information):**
- OS: Windows 10
- Minecraft 1.19.3
- Fabric Loader 0.14.12
- Fabric API 0.71.0+1.19.3
- Version 1.7.2+1.19.3

**Logs:** https://mclo.gs/lh3t8Fp

**Logs with Mod Menu enabled:** https://mclo.gs/cuuqM8x

**Comment by Shadowbreakerss** [comment]
I also have the same Problem

**Comment by foxhull** [comment]
I am also experiencing this issue. Game launches just fine with most recent Fabric/Sodium/Iris. Adding MidnightControls causes crashing.

**Comment by Kichura** [comment]
Downgrading to fabric api 0.70.0 resolves it for now.

**Comment by Motschen** [comment]
Fixed in 1.7.3, have fun :)
