### ISSUE TITLE
Midnight Controls Keep crashing Minecraft!!!!

### ISSUE THREAD

**Issue by KissMyClass0909** [TeamMidnightDust/MidnightControls#157]
the game is up to date and so are my other mod too but when I load Minecraft it keeps crashing saying it midnight controls it was working fine yesterday but today load it and now it keep crashing and I even disable the mod and the game loads right up so don't know what happen to this mod but it needs an other fix cause I really love this mod for Minecraft java. this is the crash 

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'midnightcontrols'!

**Comment by Motschen** [comment]
I just released an update addressing crashes with the new version of Fabric API, update to the latest version.
