### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [TeamMidnightDust/MidnightControls#159]
**Describe the bug**
start up game and crash

**To Reproduce**
1. Launch game
2. Crash

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Minecraft 1.19.2
 - Fabric 0.14.12
 - Mods "in the log"
 - Version 1.7.3
 - Branch [e.g. dev]

**Additional context**
https://mclo.gs/Yc3SGku

**Comment by Waoweens** [comment]
#158 might be related

**Comment by Motschen** [comment]
> #158 might be related

Yes, it is.
