### ISSUE TITLE
Steam Deck: Jittery Camera

### ISSUE THREAD

**Issue by npulsipher4** [TeamMidnightDust/MidnightControls#167]
**Describe the bug**
Whenever moving the camera it is jittery and looks like 10fps

**To Reproduce**
1. Install Prism Launcher
2. Install Fabulously Optimized
3. Launch it. Observe

**Expected behavior**
Smooth camera panning.

**Desktop**
 - OS: Steam OS
 - Minecraft 1.19.3

**Comment by Jaceideu** [comment]
I downloaded Fabulously Optimized on steam deck today, and can also confirm that this happens.

**Comment by npulsipher4** [comment]
I changed my controller settings on the deck so that my right joystick acted as a mouse and it works way better. @Jaceideu
