### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by forditt** [TeamMidnightDust/MidnightControls#170]
I completely translated MidnightControls into Ukrainian, so I hope that you will add this translation in the next version:
https://drive.google.com/file/d/1oAAc0yAiK424el8Skxnpwyz21Vz1tyfB/view?usp=sharing

I still haven't found the line responsible for "Reset", so I'll leave the translation here: `Reset - Скинути`
![зображення](https://user-images.githubusercontent.com/105544922/216350537-2b8792be-a131-4ccb-9170-6a7cf59bbe5c.png)

**Comment by Motschen** [comment]
Thank you very much, I'll make sure to add it in the next version ;)

**Comment by Motschen** [comment]
Added in 1.8.1, thanks again!
