### ISSUE TITLE
TOUCHSCREEN DON'T WORK CUH!

### ISSUE THREAD

**Issue by AdolfRoxler** [TeamMidnightDust/MidnightControls#175]
**Describe the bug**

**To Reproduce**
- Use a literal phone
- Touchscreen mode
- mfw touchscreen buttons don't work

**Expected behavior**
Touchscreen buttons should work
**Screenshots**

**Desktop (please complete the following information):**
 - OS: postmarketOS
 - Minecraft 1.19.3
 - Fabric 0.14.15
 - Mods Midnightcontrols, fabric api, starlight, sodium, no chat reports, no telemetry, iris shaders, mod menu, multiconnect, chat heads
 - Version 1.7.3
 - Branch (I think it's main because there's no dev mention)

**Additional context**

Unofficially running it on a Oneplus 6. Minecraft indeed detects my fingers.

**Comment by asdfghjkl403622** [comment]
I am having the same issue on mobian with my pinephone pro, except I can't even navigate menus.

**Comment by asdfghjkl403622** [comment]
just read #20 , this issue should probably be closed
