### ISSUE TITLE
Can't break blocks!

### ISSUE THREAD

**Issue by withered-coffee** [TeamMidnightDust/MidnightControls#176]
**Describe the bug**
Running two Minecraft instances at one time. When one instance is out of focus the controller is unable to break block when with “Unfocused Input” selected 

**To Reproduce**
1. Create and open one instance of Minecraft 
2. Create another open instance of Minecraft on the same a computer. Configure instance 1 midnight controls to connect with controller and enable unfocused input.
3. Open a world on both
4. Use F3+p in both instances to stop auto pausing
5. While using instance two (with a keyboard and mouse for an example) you should be able to move around swing hit and other things while using the controller on instance one
6. However am unable to break blocks with controller trigger

**Expected behavior**
While using Unfocused input option the controller should be able to break blocks while not in focus

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.18.2
 - Fabric 0.14.14 (I think)
 - Mods midnightcontrols
 - Version [e.g. 11.5.0+1.18
 - Branch [e.g. dev]

**Additional context**

**Comment by withered-coffee** [comment]
I'm stupid Virtual mouse is now enabled

**Comment by withered-coffee** [comment]
If doing split screen on one PC virtual mouse fixed small things like breaking blocke

**Comment by Gamerbiomek2** [comment]
Can't break blocks in Survival mode in 1.20.4
