### ISSUE TITLE
Possible split screen?

### ISSUE THREAD

**Issue by goofymctooty** [TeamMidnightDust/MidnightControls#181]
I was wondering if there was planned split screen coop like in lamb controlls or any other mods that add it.

**Comment by Ivanoshechka** [comment]
MidnightControls it's a LambControlls  fork. So splitscreen is have been there for a long time. You need launch 2 clients, where one must be have MidnightControls. (If you did everything this with Lambcontrolls, nothing has changed, so you have do the same thing to play.) 
:)

**Comment by Ivanoshechka** [comment]
If not. So...
 > Launch minecraft with mod.

![изображение](https://user-images.githubusercontent.com/88715280/225326721-aaa311f3-0626-41f8-8618-c6036b2b04d2.png)

 > Go to go Settings`/`Controls...`/`The small controller button.

![изображение](https://user-images.githubusercontent.com/88715280/225328425-7080af37-c7e4-481e-a232-84aef81108c4.png)

 > Now turn on the virtual mouse in `General Options`. And in `Controller Options` set unfocused input.

![изображение](https://user-images.githubusercontent.com/88715280/225329377-6db7e016-deb8-48fd-bea2-2540862d73a2.png)

 > Now gtg to world. Press `F3 + P` to disable pause on lost focus.

![изображение](https://user-images.githubusercontent.com/88715280/225329803-f3c81e65-b8e0-4e93-8a59-f4f6234eb87c.png)

 > Now you can play. :)

https://user-images.githubusercontent.com/88715280/225333996-d8f7c754-c967-4232-ac1b-02bfaa7f60d3.mp4



 (If you have the mod like "Dynamic FPS" turn it off.)
 
![изображение](https://user-images.githubusercontent.com/88715280/225330728-574a8f1d-084d-4a46-a3da-e4896de4accb.png)

**Comment by Shadowblitz16** [comment]
It would be nice if you guys could support actual split screen instead of us having to deal with launching multiple mine craft instances and manually rearrange them each time.

Maybe something like bedrock.

**Comment by Motschen** [comment]
Thanks Ivanoshechka for your detailed and well-written guide :)
I'll take inspiration from that when writing the upcoming Wiki.
As for split screen in one single instance: I don't think that'd be feasible without a significant rewrite of the Minecraft codebase. Minecraft Java is made only with one single local player in mind. The only possibility for that is if Mojang decides to implement it themselves, but a mod would simply be a pain to update and add mod support for.
