### ISSUE TITLE
Ukrainian translation 

### ISSUE THREAD

**Issue by forditt** [TeamMidnightDust/MidnightControls#184]
oh no, my Ukrainian translation was not added in the new version of the mod.. May I know why?
![зображення](https://user-images.githubusercontent.com/105544922/225432209-a3b49bba-24f9-4ebe-be68-dd83225134db.png)

**Comment by Motschen** [comment]
Oh, sorry, I just overlooked it since translations are usually handled via PR requests, not via the issues tab.
I'll include it in the coming bugfix update.

**Comment by Motschen** [comment]
Added in 1.8.1 ;)

**Comment by forditt** [comment]
Thank you very much 🐢
