### ISSUE TITLE
Unable to use left joystick in inventory after update to 1.8.0 - 1.19.4 

### ISSUE THREAD

**Issue by PawelJ-PL** [TeamMidnightDust/MidnightControls#185]
**Describe the bug**
After uodate to `1.8.0 - 1.19.4` left joystick is no longer working in inventory. I can navigate between slots only with dpad arrows. 

**To Reproduce**
1. Update to version `1.8.0 - 1.19.4`
2. Reset controller settings to default (optional step) 
3. Start game
4. Open inventory 
5. Try to use left joystick to navigate

**Expected behavior**
When using joystick on inventory screen, cursor should appear and I should be able to select slot or item using it 

Tested on Steam Deck

**Comment by nin10dofinatic** [comment]
I’m also experiencing this problem. 

I also have my close menu button set to the same button as my crouch/sneak and I seem to crouch every time I close a chest, which makes opening the next chest only possible by uncrouching every time. I guess both prompts are happening super fast after each other?

**Comment by NHRY719** [comment]
Java 1.19.4, Fabric latest release, Xbox one controller Bluetooth connection

**In survival mode**
Left joystick will not work when accessing inventory menu or an interactive block menu such as the furnace, chest
-D Pad works
(Always use left stick as mouse, active)

**In creative mode**
Left joystick will work properly in all menus (Always use left stick as mouse, active)
