### ISSUE TITLE
The virtual mouse is invisible

### ISSUE THREAD

**Issue by KennyDevT** [TeamMidnightDust/MidnightControls#189]
**Describe the bug**
The Title

**To Reproduce**

Enable Virtual Mouse

**Expected behavior**
The virtual mouse should be visible

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.19.4
 - Quilt 0.19.0-beta.6
 - Version 1.8.1

**Comment by Garwinium** [comment]
I am having the same issue on fabric 1.19.4, also with mod version 1.8.1 with windows
edit: also the windows mouse cursor remains visible at all times, idk if this is related
edit 2: also after closing and reopening any menu the virtual cursor goes to the top left so I have to go down and to the right to access the menu

**Comment by MidyGamy** [comment]
Same issue

**Comment by MagiusCHE** [comment]
same issue here :-(

PLZ it is unable to play with joypad!!! someone has a workaround to this?

**Comment by dennore** [comment]
Same issue for me...
I currently play 4player splitscreen with 4 controllers on forgeloader with controllable which is fine... but struggle with fps a bit...

Now i want to have VulkanApi cause it runs 60+fps with 4 instances...
However Vulkan seems only available on fabric

Now my issue i have invisible mouse cursor issue

OS windows
Mc 1.19.4
Fabric 0.14.19
Midnight 1.8.1
DS4Windows with 4xds4 controllers converted to xbox (hidhide physical)

**Comment by galvianistudioeco** [comment]
Plz guys, this is a MAJOR bug!!! The game is unplayble without the virtual mouse or.. anyone has a workaround to show or simulate it with other settings/mods?

**Comment by dennore** [comment]
Downgrade to mc version 1.18.x worked for me...

**Comment by MagiusCHE** [comment]
> Downgrade to mc version 1.18.x worked for me...

Unfortunately cant downgrade mc version....

btw i started to use [Controllable](https://github.com/MrCrayfish/Controllable) that seems to handle pointer without issue. But it lacks of a multiinstances bug (at least for me). If you dont use multiistance it should solve the problem.

**Comment by dennore** [comment]
Yes on the new Controllable (fabric) i have to change the inputs for player 2-4 every time i start. Because it can only autoselect the first controller :-( 

Maybe you can try vote here for MrCrayfish to implement it.

https://github.com/MrCrayfish/Controllable/issues/383

**Comment by KennyDevT** [comment]
Fixed in update

**Comment by Razatop** [comment]
What version was this fixed in? Your/Our issue is still around cause 1.8.1 is still the latest version.
