### ISSUE TITLE
Can't get Steam Deck inbuilt controller to work, even with mappings.

### ISSUE THREAD

**Issue by superluig164** [TeamMidnightDust/MidnightControls#198]
**Describe the bug**
The built in Steam Deck controller seems to not want to work, no matter what I try.

**To Reproduce**
1. Install Minecraft.
2. Use Fabric's jar installer to install Fabric.
3. Install MidnightControls.
4. Use a sensible controller mapping (gamepad with mouse trackpad in my case)
5. Observe that the "controller" screen is listed red with the name "0"
6. Attempt to create a custom mapping in desktop mode
7. Paste it into the editor
8. Observe that the "controller" screen is listed red with the name "0"
9. Give up and make a post here (lol)

**Expected behavior**
I expected MidnightControls to just detect the steam virtual gamepad.  Neither in desktop mode or gaming mode does it detect it.

**Desktop:**
 - OS: SteamOS (Arch Linux)
 - Minecraft 1.19.3
 - Fabric 0.14.19
 - Version 1.7.3
<details>
<summary>Mods</summary>

**AmbientSounds**                                 Modrinth   fM515JnW
**Auditory**                                      Modrinth   1LjfkWOR
**AutoSwitch**                                    Modrinth   uSdcnlts
**Axolotl Buckets**                               Modrinth   6tlhZmC5
**Balm**                                          Modrinth   MBAkmtvl
**Blur (Fabric)**                                 Modrinth   NK39zBp2
**Chat Heads**                                    Modrinth   Wb5oqrBJ
**Chunks fade in**                                Modrinth   JaNmzvA8
**Clear Skies**                                   Modrinth   xNK6XfRv
**ClearDespawn**                                  Modrinth   yoJJjRRE
**ClickThrough**                                  Modrinth   Z5b0cAlD
**Client Tweaks**                                 Modrinth   vPNqo58Q
**Cloth Config API**                              Modrinth   9s6osm5g
**Continuity**                                    Modrinth   1IjD5062
**Crafting Tweaks**                               Modrinth   DMu0oBKf
**CreativeCore**                                  Modrinth   OsZiaDHq
**Distant Horizons**                              Modrinth   uCdwusMi
**Draggable Resource Packs**                      Modrinth   aLcHfalx
**Drip Sounds (Fabric)**                          Modrinth   T8MMXTpr
**Eating Animation [Fabric]**                     Modrinth   rUgZvGzi
**Exordium**                                      Modrinth   DynYZEae
**Explosive Enhancement**                         Modrinth   OSQ8mw2r
**Fabric API**                                    Modrinth   P7dR8mSH
**Fabric Language Kotlin**                        Modrinth   Ha28R6CL
**Falling Leaves**                                Modrinth   WhbRG4iK
**FastQuit**                                      Modrinth   x1hIzbuY
**Highlight**                                     Modrinth   Vz96hXMh
**Hold That Chunk**                               Modrinth   LXJlc5WJ
**Indium**                                        Modrinth   Orvt0mRa
**Interactic**                                    Modrinth   ErpAAAaf
**Iris Shaders**                                  Modrinth   YL57xq9U
**Ksyxis**                                        Modrinth   2ecVyZ49
**Lithium**                                       Modrinth   gvQqBUqZ
**Low Fire**                                      Modrinth   Gou1gmGj
**Make Bubbles Pop**                              Modrinth   gPCdW0Wr
**MidnightControls**                              Modrinth   bXX9h73M
**MidnightControlsExtra**                         Modrinth   WajYWUam
**Mod Menu**                                      Modrinth   mOgUt4GM
**Model Gap Fix**                                 Modrinth   QdG47OkI
**Monsters in the Closet**                        Modrinth   GMA8jFBD
**Mouse Tweaks**                                  Modrinth   aC3cM3Vq
**Phosphor**                                      Modrinth   hEOCdOgW
**Presence Footsteps**                            Modrinth   rcTfTZr3
**Smooth Swapping**                               Modrinth   ydZic5r4
**Sodium**                                        Modrinth   AANobbMI
**Sodium Extra**                                  Modrinth   PtjYWJkn
**Sound Physics Remastered**                      Modrinth   qyVF9oeo
**Status Effect Bars**                            Modrinth   x02cBj9Y
**thorium**                                       Modrinth   ImUQFWcy
**Tiny Item Animations**                          Modrinth   wMkevcSR
**ToolTipFix**                                    Modrinth   2RKFTmiB
**Very Many Players (Fabric)**                    Modrinth   wnEe9KBa
**Void Fog**                                      Modrinth   JRC9aXm9
**YetAnotherConfigLib**                           Modrinth   1eAoo2KR
**Zoomify**                                       Modrinth   w7ThoJFB
</details>

**Additional context**
This is the first time I've tried using MidnightControls in any capacity, I haven't tried it on my desktop with the same mod list.  I usually play with mouse and kb.  I literally just copied my mods over to my SD and added MidnightControls on it.

**Comment by hrdkbhatnagar** [comment]
Yes, I have the same issue with my steam deck. My controller is also listed as Red with "0", and the game is not recognizing the steam deck controller at all.

**Comment by megapro17** [comment]
It doesn't see gamepad at all

**Comment by Motschen** [comment]
See #136

**Comment by superluig164** [comment]
> See #136

Lol what?  This bug was about gaming mode, not desktop mode.

**Comment by Motschen** [comment]
> > See #136
> 
> Lol what? This bug was about gaming mode, not desktop mode.

It's really hard to keep track of hundreds of issues and it slows the development (and motivation) down massively.
That's why today, I've gone through all open issues and merged related ones.
Your issue occurs on the Steam Deck and is similar to the linked one, so please comment on that one with the extra information you have about it also not working correctly in Gaming Mode.
