### ISSUE TITLE
Gamecube controller support? Maybe?

### ISSUE THREAD

**Issue by TAKfsg** [TeamMidnightDust/MidnightControls#2]
If possible or if enough people care, add support for gamecube controllers; it would be a cool feature. (Plus I'm too poor to buy a switch pro controller 😢)

**Comment by Motschen** [comment]
It'll probably work already, just not show the right buttons.
Please tell me if it works, as I don't have a gamecube controller to test it myself.

**Comment by TAKfsg** [comment]
![image](https://user-images.githubusercontent.com/73729536/166078788-cda44171-41f5-4d07-b668-a8b854093a0e.png)
This is what it looks like for me. It works fine with the Dolphin Emulator so it is not an issue with my adapter. Maybe I am stupid and missing out on something obvious.

**Comment by DioEgizio** [comment]
Did you get mappings from https://generalarcade.com/gamepadtool/ and then copied them to the "mappings file editor" section?

**Comment by TAKfsg** [comment]
It doesn't show up in gamepadtool so I think I'm gonna put this on their repo.

**Comment by Motschen** [comment]
Well, then that's probably an issue with GLFW's gamepad system, which this mod is built upon

**Comment by dude98** [comment]
Dolphin emulator uses the gamecube adapter directly, it's not recognized on pc by default, so it wouldn't read it. you'd need either WiinUPro to emulate an Xbox (XInput) Controller, or the WiiU GCN USB Driver program to emulate a DInput controller.
WiinUPro Git: https://github.com/KeyPuncher/WiinUPro/releases
WiiU GCN USB Driver: http://m4sv.com/page/wii-u-gcn-usb-driver (Has a Git on BitBucket)
they both take a little setup, but you'll be able to figure it out.

**Comment by Motschen** [comment]
Going to close this, since a workaround has been found
