### ISSUE TITLE
Incompatibility with FastLoad

### ISSUE THREAD

**Issue by LPDawid** [TeamMidnightDust/MidnightControls#202]
**Describe the bug**
Minecraft crashes when loading a world. Most of the time, screen with:

"Building terrain
Completed / Goal
Preparing All Chunks: x/x
Building Visible Chunks: x/x"

does not appear, making "Starting Session" screen the last before crash. Sometimes this screen is visible, but chunks status is not updated, frozen at 1-50/x in preparing and at 0/x in building. Loading time before crash is similar in both cases. If a new world is created, it will be saved and can be loaded later if one of the affected mods is disabled.

**To Reproduce**
Mod combination affected:
FastLoad 3.2.0-3.3.8
MidnightControls 1.7.3-1.8.1

Disabling one of affected mods fixes crashes.

No other mod, plugin, data pack, shader, resource pack loaded.

Last working mod combination:
FastLoad 3.1.1
MidnightControls 1.7.3-1.8.1

**Desktop**
Steam Deck, SteamOS 3.4.6, Prism Launcher 6.3 (flatpak stable), Fabric Loader 0.14.19,
(Minecraft 1.19.3, Fabric API 0.76.1) or (Minecraft 1.19.4, Fabric API 0.79)

**Logs**
Debug in FastLoad is set to true.
[latest.log.txt](https://github.com/TeamMidnightDust/MidnightControls/files/11345799/latest.log.txt)
[crash-2023-04-27_17.02.54-client.txt](https://github.com/TeamMidnightDust/MidnightControls/files/11345800/crash-2023-04-27_17.02.54-client.txt)
[20230427-1.json.txt](https://github.com/TeamMidnightDust/MidnightControls/files/11345801/20230427-1.json.txt)

**Comment by Kichura** [comment]
Referencing [FastLoad's issue](https://github.com/BumbleSoftware/Fastload/issues/89) here as StockiesLad requested me to do it.

**Comment by StockiesLad** [comment]
for the dev: https://github.com/BumbleSoftware/Fastload/issues/89#issuecomment-1529003230 explains my status regarding this conflict. I am curious if midnight controls is contingent upon 441 or DownloadingTerrainScreen?

**Comment by Motschen** [comment]
Likely fixed in the latest 1.20 versions. 
If it isn't, leave a comment and I'll reopen the issue.
