### ISSUE TITLE
the touchscreen option doesn't work at all.

### ISSUE THREAD

**Issue by yoni30** [TeamMidnightDust/MidnightControls#206]
when i turn on the touch option in the mod's settings, the on-screen buttons show and all but the touch still just randomly makes the screen go crazy no matter where i tap and in the keyboard only the wasd keys work.

1. Go to settings
2. Click on options
3. click on controlls
4. click on the controller logo (the mod's logo)
5. change to touchscreen mode
6. go back to game
7. bag happens 

 - OS: windows 11
 - Minecraft 1.19.4
 - Fabric latest 
 - Mods fabric fabulously optimized modpack and better pvp mod.
 - Version latest

**Comment by Butterscotch-P1e** [comment]
Same

**Comment by Cha14ka** [comment]
Same

**Comment by otomir23** [comment]
Same
