### ISSUE TITLE
[Suggestion] Seperate the controller support from the rest of the mod in a new one

### ISSUE THREAD

**Issue by RaptaG** [TeamMidnightDust/MidnightControls#21]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Create a new mod which will only include the gamepad compatibility features.

**Describe alternatives you've considered**
The user could probably disable them by their own.

**Additional context**
The extra (eg. BE parity) features such as the front block placing can be considered as cheats, which make this mod less client-side.

(Maybe name the other mod MidnightControllers?)

**Comment by Motschen** [comment]
The cheats are automatically disabled on servers that don't have explicit compat, so I don't see a need for a seperate mod.
These features are added to make playing with Controllers more enjoyable, so it makes sense to have them in MidnightControls.

**Comment by RaptaG** [comment]
> The cheats are automatically disabled on servers that don't have explicit compat, so I don't see a need for a seperate mod. These features are added to make playing with Controllers more enjoyable, so it makes sense to have them in MidnightControls.

Also, another question: Can they be disabled by the user in the config?

**Comment by Motschen** [comment]
Yes, and they're disabled by default.
