### ISSUE TITLE
Fabric 1.20.1 Crash

### ISSUE THREAD

**Issue by TheMarksmanXII** [TeamMidnightDust/MidnightControls#212]
**Describe the bug**
Whenever using the mod then I get a crash. I am not sure if one of the mods I was already using was incompatible, but I have the crash report pasted.

**Expected behavior**
I expected that Minecraft would load properly without crashing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft: 1.20.1
 - Fabric: 0.14.21
 - Mods: [Mod List](https://mclo.gs/Hm80HNd)
 - Version: 1.8.2+1.20

**Additional context**
[Crash Report](https://mclo.gs/RKJd2ZN)

**Comment by Sewdohe** [comment]
I'm also having this issue. Even removing Indium doesn't fix - just causes a different crash.

**Comment by Motschen** [comment]
Should be fixed by now
