### ISSUE TITLE
dpad unresponsiveness

### ISSUE THREAD

**Issue by loyyord** [TeamMidnightDust/MidnightControls#216]
The problem is an odd one, when i press the dpad and it will work fine, but when i try to press the dpad repeatedly, regardless of direction, it will not register all the inputs that i make. This is frustrating because i have to wait for the box highlighter thingy to move around while i repeatedly mash my dpad. 

I would like for the dpad to register all inputs to provide a more responsive experience

This issue occurred with my xbox series x controller over Bluetooth,

**Comment by Behgz** [comment]
I have encountered this issue before, I think it stems from the game trying to process a lot of heavy mods and the games input latency is slowed down. If I lower my render distance the responsiveness usually gets better, but it's frustrating when I'm walking around trying to load more terrain to see on my Xaero map with maxed out render distance, and then I casually stop to check my inventory and my d-pad is suddenly laggy as hell. When I play in an unmodded game with medium/low render the responsiveness is fine, but lots of mods plus high render causes the issues. Not sure if there's anything to fix this.

**Comment by loyyord** [comment]
really? I only have the create mod an a few other smaller performance and quality of life mods running. i didnt get around to actually playing with in it a world, i ended up just trying to navigate around the settings menus and saw the dpad was not as responsive as it should have been so i just ended up leaving it out, ill be sure to check it out in a world to see if the dpad is only unresponsive in setting menus

**Comment by Behgz** [comment]
yea, it could also be your PC/Laptop, if it's not very strong then having a light mod pack won't matter. Biggest issue after that would be render distance. When I crank it up above 32 chunks the d-pad can get laggy when using the inventory GUI. I've dealt with it for a long time now and I always lower my render distance and the issue goes away, until the next time I need to increase it and then it happens again.

**Comment by Motschen** [comment]
See #51
