### ISSUE TITLE
Waystones listed went from 40 to 6 listed

### ISSUE THREAD

**Issue by Zkiera** [TeamMidnightDust/MidnightControls#226]
**Describe the bug**
When opening the waystone menu (in Minecraft fabric mod Better Minecraft) the list of activated waystones now only lists 6 waystones. I have been actively gathering waystone locations and had more than 40 activated and even had a few named special names. Now I can’t find my main base as it was one of the mysteriously suddenly deleted or deactivated waystones. :/

**Desktop (please complete the following information):**
 - OS: 
 - Minecraft 1.20 
 - Fabric 
 - Mods Better Minecraft mod pack
 - Version 
 - Branch

Sadly I don’t know the answers to most of the above questions.

**Comment by Motschen** [comment]
MidnightControls is not related to Waystones in any way, you are likely in the wrong repository.
