### ISSUE TITLE
1.20.1 Midnight Controls - 1.8.2 GUI 

### ISSUE THREAD

**Issue by KOSKing09** [TeamMidnightDust/MidnightControls#228]
**Describe the bug**
Cursor's are trash and still behind the GUI, if used with immersive controls the controls don't work as well. The inventory button GUI With REI mod isn't able to be selected.

**To Reproduce**
1. Turn on virtual mouse
2. nothing works after that invisible inventory and so forth.

**Expected behavior**
a usable stable mod but is inoperable on version 1.20.1 which has 90% of the most current mods on it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft [e.g. 1.20.1]
 - Fabric [e.g. fabric 0.14.2]
 - Version [e.g. 1.20.1]
 - Branch [e.g. Release 1.8.2]

**Additional context**
Please fix this i need this mod for my controller players!, you can't use the most up to date version because its on 1.20.2!

**Comment by Motschen** [comment]
Fixed :)
