### ISSUE TITLE
Xbox Elite Wireless Contrller trigger not registering as being held

### ISSUE THREAD

**Issue by EAVantablack** [TeamMidnightDust/MidnightControls#229]
**Describe the bug**
Triggers when held are only recognizing as a press

**To Reproduce**
1. Install MidnightControls
2. Start a world
3. try to mine
4. game registers the trigger being held as a press and not a hold.

**Expected behavior**
Expected Trigger to register as being pressed allowing me to mine.

**Screenshots**
![Screenshot 2023-10-06 230406](https://github.com/TeamMidnightDust/MidnightControls/assets/18687977/2b750467-c457-436b-aba1-3577e0c27079)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.20.2
 - Fabric 0.14.23
 - Mods: [fabric api 0.89.3+1.20.2, Essential Mod 1.0.0, Indium 1.0.27+1.20.2, Iris 1.6.9, Lithium 0.12.0, MidnightControls 1.9.0+1.20.2, Mod Menu 8.0.0]
 - Version 1.20.2
 - Branch Release

**Additional context**
The controller is not showing up as an xbox controller and only as an Xinput device. I already tried adding mapping just in case. all the other buttons work as expected. including the triggers, they just do not register as being held down.

**Comment by Motschen** [comment]
Go to the advanced config and enable "Trigger fix" in the controller settings

**Comment by EAVantablack** [comment]
Unfortunately that didn't seem to have any effect. tried it both with it enabled and disabled still having the same problem.

**Comment by eugeneBecker** [comment]
Try to disable virtual mouse option

**Comment by EAVantablack** [comment]
Hey that actually worked! Thanks. shame thought makes navigating the menus a bit difficult but as long as I can play it's all good.
