### ISSUE TITLE
Dpad movement in inventory breaks randomly

### ISSUE THREAD

**Issue by dude98** [TeamMidnightDust/MidnightControls#23]
**Describe the bug**
When using the dpad for the inventory, it can get stuck between slots.

**To Reproduce**
open a survival world
set hud scale to 2
go into your inventory
scroll around a bunch with the dpad
it gets stuck somewhere randomly

**Expected behavior**
you hsould be able to switch between every single slot without it bugging once in any direction

**Desktop (please complete the following information):**
 - OS: Win 10
 - Minecraft 1.18.2
 - Fabric 0.13.3 - 1.18.2
 - Mods (appleskin 2.4.0, architectury 4.4.56, bedrockify 1.4.1, collective-fabric 4.26, ears fabric 1.4.5, fabric api 0.51.1, guiclock-fabric 3.0, inventoryhud-fabric 3.4.2, lambdabettergrass 1.2.3, lambdynamiclights 2.1.0, midnightcontrols 1.0.0, phosphor 0.8.1, REI 8.1.457, sodium 0.4.1 build 15, xaeros minimap 22.7.0, xaerosworldmap 1.21.2)
 - Version 1.0.0
 - Branch release
 - Additional Info
 It might happen as well just with midnightcontrols and fabric api, i know lambdacontrols did this without any other mods so if you haven't changed anything there then it should still happen.

**Comment by dude98** [comment]
another note: i have multiple things in the lambdacontrols issues list, and i'm gonna link them here in case they still happen on this version.
Mouse Still Visible when ingame: https://github.com/LambdAurora/LambdaControls/issues/65
Quick Move activates when opening inventory: https://github.com/LambdAurora/LambdaControls/issues/63
Original Dpad Inventory Bug Link: https://github.com/LambdAurora/LambdaControls/issues/62

(Improvement) Floating Hotbar and Custom Inventory Binding (Y is open/close, B is Quick Move, etc.) https://github.com/LambdAurora/LambdaControls/issues/64

thanks for reading, this mod has been awesome.

**Comment by Motschen** [comment]
I already fixed the quick move bug, I'll look into the others though.

**Comment by Motschen** [comment]
I can't seem to replicate the Dpad movement bug, but I've now added the possibility to change inventory keybinds as requested.
The mouse visibility issue seems invalid to me, as the cursor is hidden in-game and only shown in menus, which is the way it's supposed to. I likely won't implement the floating hotbar, as MidnightControls isn't aiming for bedrock parity, users can just install Bedrockify like you did.

**Comment by Motschen** [comment]
Feel free to open again if you have verified the Dpad bug also happens with MidnightControls.
