### ISSUE TITLE
Fix or allow users turn off the "flick stick" thingy.

### ISSUE THREAD

**Issue by Ivanoshechka** [TeamMidnightDust/MidnightControls#230]
**Describe the bug**
I guess with rewritten joystick input, we now have a flick stick innovation. Like, you just need flick fast joystick to dash look or smth in this way. I hate this feature, i feel uncomfortable with this, just something not right for me.

**To Reproduce**
1. Go to world.
2. Start flick stick.
3. See fast dash movements. When there shouldn't be any. 

**Expected behavior**
Moreeee relaxed movements, like in older versions. (1.8.1 and below.)

**Screenshots**
[Youtube video. (Not compressed)](https://youtu.be/gw2LcJd6lgo)
[Discord video. (Download)](https://cdn.discordapp.com/attachments/1043801147783266375/1160154022167199824/2023-10-07_15-45-29_1_1.mp4?ex=6533a0a1&is=65212ba1&hm=855dca5fc4d9c9b0386c72721ad04190969fe49737ba806ce8945d4bddf7af0b&)
(You can look at my hand to see it twitching.)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft: 1.20.2
 - Fabric: Fabric 0.14.22
 - Mods: [List.](https://cdn.discordapp.com/attachments/1043801147783266375/1160155515087753306/image.png?ex=6533a205&is=65212d05&hm=b7e36d52f5221ff62c5f3e3e3fb3d06b24f51cba8cae20bd06438ff52eaf777e&)
 - Version: 1.9.0
 - Branch: Release.
 
**Additional context**
Oh and btw, it is there if you just move the joystick. The first seconds are a dash, then a normal movement.

**Comment by Ivanoshechka** [comment]
HB By the way!!!!

**Comment by SmashbrosThe3rd** [comment]
I also feel this new stick-aiming system is off. If you slowly increase the stick value, it's not noticeable or barely so. If you sharply increase the value (0-1 right away), it sharply turns and then slows very quickly. It almost feels like the polar value is being registered in the game and then corrected post-input to the lower, intended value. If this is some sort of intended flick-stick feature, I would like the option to toggle this. The way this feels is very unnatural and hinders gameplay.

Windows 10 22H2, Fabric Loader 0.14.23, only installed mods are MC 1.9.0 (Release) and FabricAPI 0.90.0.

**Comment by nin10dofinatic** [comment]
Ok glad this wasnt just me, Smashbros said it perfectly

**Comment by 0x464e** [comment]
I just downloaded the mod and encountered this exact issue.  
For the first split second, my camera will turn extremely fast, and then go back to the normal turning speed.

Unfortunately I must say that this mod is completely unusable with this bug.

Any chance you found some fix? @Ivanoshechka @SmashbrosThe3rd @nin10dofinatic

**Comment by Ivanoshechka** [comment]
> I just downloaded the mod and encountered this exact issue.  
> For the first split second, my camera will turn extremely fast, and then go back to the normal turning speed.
> 
> Unfortunately I must say that this mod is completely unusable with this bug.
> 
> Any chance you found some fix? @Ivanoshechka @SmashbrosThe3rd @nin10dofinatic 

In this mod - no. I started using different alternatives. Like Controlify. Good mod too. Or. Using steam input (big picture).

**Comment by 0x464e** [comment]
> > I just downloaded the mod and encountered this exact issue.
> > For the first split second, my camera will turn extremely fast, and then go back to the normal turning speed.
> > Unfortunately I must say that this mod is completely unusable with this bug.
> > Any chance you found some fix? @Ivanoshechka @SmashbrosThe3rd @nin10dofinatic
> 
> In this mod - no. I started using different alternatives. Like Controlify. Good mod too. Or. Using steam input (big picture).

Thanks, switched to that mod and it works nice.  
Not sure what I think of its forced(?) toggle sprint and crouch. I guess it for sure is easier, but imo it also teaches bad habits since that's not usually how especially sprinting is supposed to work for controller gaming.
