### ISSUE TITLE
Camera feels incredibly janky with the new system

### ISSUE THREAD

**Issue by quotejericho** [TeamMidnightDust/MidnightControls#232]
**Describe the bug**
The camera feels incredibly stiff on controller, like to such an egregious extent I've found myself preferring to use the touchpad.

**To Reproduce**
1. Use a PS4 Controller on Mac
2. Compare it to pre 1.20.2 update and now

**Expected behavior**
Smooth Camera controls similar to console rather than it feeling like it was taking direct/raw input values

**Desktop (please complete the following information):**
 - OS: MacOS
 - Minecraft 1.20.2
 - Fabric 0.14.22
 - Mods Many, but none that would affect anything controllers [Vanilla-esque/performance mods]
 - Version 1.90
 - Branch main release(?) 

**Additional context**
I love this mod and appreciate all the hard work it took and continues to take to maintain this mod, however this new rework feels incredibly terrible. Perhaps this is just a macOS issue but I would genuinely love if this was fixed, thank you.

**Comment by nin10dofinatic** [comment]
Im on pc with xbox series controller but I got similar issues. The camera for me turns super fast at the start of my control stick tilt, but then turns smooth. Even if i have settings with turned down responsiveness the start of my camera turns feel FAST and its disorienting

**Comment by ghost** [comment]
> Im on pc with xbox series controller but I got similar issues. The camera for me turns super fast at the start of my control stick tilt, but then turns smooth. Even if i have settings with turned down responsiveness the start of my camera turns feel FAST and its disorienting.

Im having the same issue, whenever i try to look around it kind of flicks a short distance before rotating properly, and when I move the right stick in a circle it makes me look around in a square pattern instead, I am also on dualsense on 1.20.2
