### ISSUE TITLE
Controller not being recognized on steam deck. using main controller on base version of minecraft I set up using fabric.

### ISSUE THREAD

**Issue by saltonkil** [TeamMidnightDust/MidnightControls#233]
![image](https://github.com/TeamMidnightDust/MidnightControls/assets/32005290/c10acc90-27a3-4f5c-8e23-bd09453a32b4)

I get absolutely no input from my controller or mouse for some reason it doesnt recognzie I even have a controller

**Comment by Motschen** [comment]
It is known that, for whatever reason, controller input doesn't work in desktop mode. However, it works perfectly fine in game mode, at least on my Deck.

**Comment by saltonkil** [comment]
> It is known that, for whatever reason, controller input doesn't work in desktop mode. However, it works perfectly fine in game mode, at least on my Deck.

even in gaming mode it doesn't work, I don't think it really matters if your using the launcher off the discovery store made by Mojang.

**Comment by Sidilium** [comment]
Try using this in your steam shortcut, while using prismlauncher ( thats how I do it, you can also use another launcher )

`env GAME_PRELOAD="/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so" sh -c 'flatpak run org.prismlauncher.PrismLauncher -l <MINECRAFTINSTANCE>'` 

source: https://steamcommunity.com/app/221410/discussions/3/2913220877914203628/

**Comment by Motschen** [comment]
@saltonkil does the fix Sidilium provided solve this issue for you? 
I can't seem to reproduce it on my own Steam Deck

**Comment by Motschen** [comment]
Please continue on #136
