### ISSUE TITLE
Controller recognized, input not processed

### ISSUE THREAD

**Issue by ghost** [TeamMidnightDust/MidnightControls#238]
**Describe the bug**
I have my controller (Xbox One Series S, Wireless and Wired both tested) connected and MidnightControls installed on Minecraft 1.20.2. The controller is recognized in the configuration menu, but none of my inputs are being processed.

I've verified that the controller and its inputs are recognized by the OS both through the built-in Game Controller settings in KDE Plasma, and an [online gamepad tester](https://hardwaretester.com/gamepad).

**To Reproduce**
1. Launch game with MidnightControls and controller connected.
2. Try to input movement, interactions or menu navigation.
3. MidnightControls does not process input.

**Expected behavior**
Controller inputs are processed, character moves, inventory opens, items are used, etc.

**Screenshots**
[Screenshot: controller is recognized properly in config menu](https://i.imgur.com/d3jxQH3.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39 Beta, running Prism Launcher under Flatpak.
 - Minecraft 1.20.2
 - Quilt 0.21.2-beta.4
 - Mods: Cloth Config, Continuity, EntityCulling-Fabric, Fabric API, Fabric Language Kotlin, FerriteCore, Iris, Krypton, LazyDFU, Lithium, **MidnightControls (1.9.0+1.20.2)**, **MidlightLib (1.5.0)**, Mod Menu, Mouse Tweaks, No Chat Reports, Reese's Sodium Options, Sodium, Sodium Extra, Starlight, YetAnotherConfigLib, Zoomify
 - Branch: release

**Comment by MXGaming1YT** [comment]
I am having the same problem but also on normal fabric

**Comment by Motschen** [comment]
Does the controller name appear in orange?

**Comment by ghost** [comment]
> Does the controller name appear in orange?

As seen in the screenshot, yes.

**Comment by Motschen** [comment]
### FAQ:
#### The controller does not work, and it's name appears in orange, what can I do?  
Orange controller names indicate a missing controller mapping.  
Download [GamepadTool](https://generalarcade.com/gamepadtool/), create and copy a mapping, go to MidnightControls' Mappings File Editor and paste the string.  
Alternatively, you can use [AntiMicroX](https://github.com/AntiMicroX/antimicroX) to create the mappings, in case the Gamepad Tool is not working for you.  
If that works, you might as well consider submitting the mapping by opening a PR in this repo: https://github.com/gabomdq/SDL_GameControllerDB  
That will make sure other people using the same controller as you don't have to use gamepad-tool anymore.

**Comment by Motschen** [comment]
It seems like I only added the FAQ to the CurseForge page, I'll add it to this project's wiki and on Modrinth too.
