### ISSUE TITLE
My MidnightControls won't work

### ISSUE THREAD

**Issue by MXGaming1YT** [TeamMidnightDust/MidnightControls#239]
**Describe the bug**
My controller won't work even though it's recognised.

**To Reproduce**
1. Plug in controller
2. Try and do anything
3. there's the bug
**Expected behavior**
I should be able to move

**Screenshots**
not letting me upload

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.20.2
 - Fabric: Latest Version (November 3rd, 2023)
 - Mods: Feather Client, MidnightControls, Sodium, Mod Menu
 - Version: Latest Version (November 3rd, 2023)

**Comment by Motschen** [comment]
In which color does the controller's name appear?
Also, make sure to select "Controller" as the controls mode.

**Comment by Motschen** [comment]
Read the new FAQ section to fix it
