### ISSUE TITLE
Touch controls for Ubuntu desktop devices

### ISSUE THREAD

**Issue by InfiniXDerg** [TeamMidnightDust/MidnightControls#240]
**Is your feature request related to a problem? Please describe.**
Feature request
Add the option to use touch mode for Ubuntu Desktop devices

**Describe the solution you'd like**
A toggle of enable or disable touch if touch device cannot be detected automatically like on Ubuntu Desktop

**Describe alternatives you've considered**
None

**Additional context**
Ubuntu Desktop devices with touch now works (22.04, recently installed it on a laptop that I've found on the trash) so I suggest the feature to detect or make a toggleable of toggle on touch if touch isn't detected on
Using Ubuntu Desktop 22.04 with a Hewlett Packard laptop, 240 G2

**Comment by Motschen** [comment]
You can simply set the ControlsMode to Touchscreen, works especially well on the 1.20.2 version, as well as the one I'm currently developing for 1.20.4
