### ISSUE TITLE
Changing key bindings won't work with PS4 controller

### ISSUE THREAD

**Issue by Oamge** [TeamMidnightDust/MidnightControls#241]
When changing key binding on ps4 controller, for example jump from "X" to "O", the controller freeze.
After restarting the game the bindings are not changed and controller works as before the change.

**To Reproduce**
1. Go to 'controller bindings'
2. Change the key of any action

**Desktop**
 - OS: Mac OS Sonoma 14.0
 - Minecraft 1.20.2
 - Fabric 0.14.24
 - Mods: Midnight Controls, Mod Menu, Sodium, Iris
 - Version: 1.9.0

**Additional context**
Unbinding the action to no key works, controller won't freeze.

**Comment by adamgulde** [comment]
I have the same issue with a Nintendo Switch pro controller.

**Comment by Motschen** [comment]
Fixed in a recent update, make sure you use the latest MidnightControls version.
