### ISSUE TITLE
MidnightControls blocking all controller input after changing a button mapping

### ISSUE THREAD

**Issue by Blade04208** [TeamMidnightDust/MidnightControls#244]
**Describe the bug**
When changing any button mapping, all controller input gets blocked.

**To Reproduce**
1. Go to Controller Mappings
2. Click on any mapping to change it
3. Input a mapping and exit the MidnightControls Menu and exit to game
4. All control is blocked

**Expected behavior**
Control should resume as nomal with the mapping applied.

**Screen Recording**
https://github.com/TeamMidnightDust/MidnightControls/assets/74104258/45a1d5cf-5e1e-4184-8165-5dca6798acd1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.20.2
 - Fabric Loader 0.14.4
 - Mods: [Fabulously Optimized Modpack](https://github.com/Fabulously-Optimized/fabulously-optimized) 5.5.1 **Without Controllify**
 - Version: 1.9.0
 - Branch: Main

**Additional context**
This may be related to #235 
I use the 8BitDo Ultimate Bluetooth Controller.

**Comment by Motschen** [comment]
Fixed in 1.9.1 and higher
