### ISSUE TITLE
Steam Deck "Guide" Key???

### ISSUE THREAD

**Issue by GoldenFurredFox** [TeamMidnightDust/MidnightControls#247]
**Describe the bug**
By default, "Open Unbound Keybind Ring" is bound to a "Guide" key that doesn't exist on the Deck's game pad, or potentially does but is used as the effective home key that opens the task switcher when used in gaming mode and opens the main steam window when used in desktop mode.

**To Reproduce**
1. Look into midnight controls GUI
2. Go to controller bindings
3. Look at the bind for open unbound keybind ring
4. Try to assign literally any other assignable key and discover that none of them are the guide key

**Expected behavior**
The control would be bound to a usable key by default

**Screenshots**
![28df577e-e5a8-4c89-8661-86cb7fc23ee5](https://github.com/TeamMidnightDust/MidnightControls/assets/28793227/79e24069-cb13-470b-a292-c43d242c1264)

**Desktop (please complete the following information):**
 - OS: Linux/SteamOS
 - Minecraft: 1.19.2
 - Fabric: 0.15.0
 - Mods: Long list that I'll need to fetch in a little bit; I'll edit this soon.
 - Version: 1.7.4 (Extras 1.0.0)
 - Branch: Stable? I think? I got it from Modrinth through Prism Launcher and my settings shouldn't technically allow betas or alphas, so...

**Additional context**

**Comment by Motschen** [comment]
The guide key only works without Steam open, so you should probably just bind it to something else.
