### ISSUE TITLE
Left click is jammed and requires button to be held

### ISSUE THREAD

**Issue by Kichura** [TeamMidnightDust/MidnightControls#251]
**Describe the bug**
When trying to use left click on default keybind, the button is jammed and requires the button to be held.

**To Reproduce**
1. Install MidnightControls 1.9.1,
2. Start up the client without any configs changed,
3. Join any world,
4. Try to left click,
5. Realize it requires button to be held instead of normal clicks.

**Expected behavior**
Left clicking does not require button to be held down.

**Screenshots**
*(Cannot provide screenshots for this one)*

**Desktop (please complete the following information):**
 - OS: Linux,
 - Minecraft: 1.20.4,
 - Fabric: 0.82.0,
 - Mods: MidnightControls,
 - Version: 1.9.1
 - Branch: 1.20.4.

**Additional context**
This is likely caused by a touch-related fix that managed to conflict with the left-clicking functionality at the same time.

**Comment by Motschen** [comment]
This was caused by a small oversight on my end, I just pushed out a fix.
Thanks for reporting :)
