### ISSUE TITLE
nintendo switch pro controller

### ISSUE THREAD

**Issue by temginson** [TeamMidnightDust/MidnightControls#252]
**Describe the bug**

**To Reproduce**
my Nintendo Switch pro controller dose not work in game

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 insider
 - Minecraft 1.20.2
 - Fabric feather
 - Mods [e.g. aurora_keystrokes v1.0.0, modmenu v1.7.15]
 - Version [e.g. 1.9.0
 - Branch [e.g. dev]

**Additional context**

**Comment by Motschen** [comment]
See #10
