### ISSUE TITLE
Cant break blocks when unfocused [1.20.2-1.20.4]

### ISSUE THREAD

**Issue by UGLSD** [TeamMidnightDust/MidnightControls#253]
**Describe the bug**
In 1.20.2-1.20.4 it is not possible to break blocks when game is not in focus

**To Reproduce**
1. Start 2 Instances of Minecraft in Version 1.20.2
2. Enable unfocused input and Virtual Mouse in Settings
3. Try breaking blocks
4. See bug

**Expected behavior**
Should be able to break blocks when game is unfocused

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Minecraft [1.20.2-1.20.4]
 - Fabric [e.g. fabric 0.7.2+build.174]
 - Mods [Only MidnightControls and Fabric API]
 - Version [1.9.2]
 - Controler [Xbox 360 Wired Controller]

**Comment by Motschen** [comment]
Can you test if this is fixed in 1.9.3?

**Comment by Rodostlyn69** [comment]
> Can you test if this is fixed in 1.9.3?

Isn't fixed in 1.9.3, I can't break blocks either

**Comment by Motschen** [comment]
Fixed in 1.9.4
