### ISSUE TITLE
cannot move on steam deck

### ISSUE THREAD

**Issue by a7x492** [TeamMidnightDust/MidnightControls#254]
**Describe the bug**

Trying this mod for the first time. I cannot move on the Steam Deck. The right analog stick is able to look around and all the other buttons steam to work. Only the left analog stick is not working and therefore I cannot move.

**To Reproduce**
1. Start a new game
2. Try to move
3. Observe that you cannot move

**Expected behavior**

Being able to move

**Desktop (please complete the following information):**
 - OS: Steam Deck
 - Minecraft 1.20.4
 - Fabric 0.92.1
 - Mods modmenu 9.0.0 midnightlib 1.5.3
 - Version 1.9.2

**Additional context**

Also tried controlerify and had the exact same issue. Googled this a lot, and found nothing useful. Does nobody else have this issue? Or is nobody else even trying to get this to work on Steam Deck?

**Comment by Motschen** [comment]
Are you able to navigate menus using the left stick?

**Comment by Motschen** [comment]
See #136
