### ISSUE TITLE
Cant break blocks constantly and the progress of breaking a block will be "saved" on 1.20.4

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [TeamMidnightDust/MidnightControls#255]
**Describe the bug**

**To Reproduce**
1. Get into a server
2. Try to break a block
3. Then the move away your crosshair before you completely break the block, the block seems frozen and the progress of breaking a block will be "saved", after a few seconds, you can still continue your breaking progress of the block and it just takes few seconds to block it (if you have almost break the block before this). Also, everytime you click the mouse, you are only able to break one block.

**Expected behavior**
play game normally

**Screenshots**
![2024-01-10_20 49 49](https://github.com/TeamMidnightDust/MidnightControls/assets/42903464/548263d3-725a-4321-b6a5-bbf3a9e3c3cf)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Minecraft [1.20.4]
 - Fabric [e.g. fabric 0.15.3]
 - Mods [only midnight control]
 - Version [e.g. 1.9.1]

**Additional context**

**Comment by Kichura** [comment]
Can confirm, and this is much worse on MCC island where trying to break crates on dynaball does not trigger.

**Comment by Motschen** [comment]
Did you change any settings related to touch?
