### ISSUE TITLE
I can't hold down the triggers while virtual cursor is turned on.

### ISSUE THREAD

**Issue by Fankraker** [TeamMidnightDust/MidnightControls#257]
When i turn on the "Virtual Cursor" feature in the controller settings, i notice that i cannot break blocks with the triggers because when i try to hold them down, they do not continue breaking.

To Reproduce
1. Go to 'Midnight Controls - Settings'
2. Click on 'Virtual Mouse'
3. Try breaking a block with a trigger mapped to the action.

Expected behavior
When the trigger is held down, my fist punches once but does not continue breaking blocks.

Desktop
 - OS: [Ubuntu Linux 22.04.3]
 - Minecraft [1.20.4]
 - Fabric [e.g. fabric 0.15.3]
 - Mods [Zoomify-2.12.0, XaerosWorldMap_1.37.6, Xaeors Minimap_23.9.6 ,XaeroPlus visuality-0.7.3, sodium-0.5.5, moreculling-0.19.0 modmenu-0.0.0-pre1 iris-mc-16.14 fabric-language-kotlin-1.9.22, fabric-api-0.91.2 custom-crosshair-mod-1.5.3 cloth-config-13.0.121 appleskin-2.5.1]
 - Version [1.9.2]

**Comment by ghost** [comment]
This is still broken on fresh installs of:

* Minecraft 1.20.1
    * Fabric 0.15.6
    * Fabric API 0.91.1+1.20.1
    * MidnightControls 1.9.3+1.20
    * MidnightLib 1.4.1
* Minecraft 1.20.4
    * Fabric 0.15.6
    * Fabric API 0.95.4+1.20.4
    * MidnightControls 1.9.3+1.20.4
    * MidnightLib 1.5.3

With no other mods, on Linux (NixOS 23.11) with Prism Launcher 8.0.

**Comment by Motschen** [comment]
Fixed in 1.9.4

**Comment by Motschen** [comment]
For real this time ;)

**Comment by ghost** [comment]
Confirmed working. Thank you!  :)
