### ISSUE TITLE
Loot Creates in MCC Island's dynaball never break

### ISSUE THREAD

**Issue by Kichura** [TeamMidnightDust/MidnightControls#258]
**Describe the bug**
When playing on MCC Island but in the minigame Dynaball, Loot and TNT crates cannot be broken until MidnightControls itself is disabled entirely.

**To Reproduce**
1. Log on to the MCC Island server with any faction,
2. Join the minigame dynaball using any round,
3. Look for a TNT / Loot Crate,
4. Try to mine it and notice it never breaks.

**Expected behavior**
Loot / TNT crates can be broken for items.

**Screenshots**
*(No screenshots for this can be provided, Sorry)*

**Desktop (please complete the following information):**
 - OS: Linux
 - Minecraft: 1.20.4
 - Fabric: 0.15.6
 - Mods: Fabric API (0.95.1+1.20.4)
 - Version: 1.9.2+1.20.4
 - Branch: 1.20.4

**Additional context**
I may be certain that this issue is related to #255 although very consistent when playing on this server as example, However it's likely to be another cause from Touch-related features or something else that impacts them.

**Comment by Motschen** [comment]
This is likely fixed in the new version, lmk if it really is

**Comment by Kichura** [comment]
Works as intended now.
