### ISSUE TITLE
Problems with EMI

### ISSUE THREAD

**Issue by AnyaPizza** [TeamMidnightDust/MidnightControls#261]
When I launch Minecraft it gets to the red loading screen and then the game crashes. if I roll back a version it works for a bit and then crashes again in a few minutes.

1. Launch Minecraft with EMI and Midnight Controls.

Expected behavior:
Game runs.

 - OS: Windows 11
 - Minecraft 1.21.1
 - Fabric 0.15.6
 - Mods: 
 advancednetherite-fabric-2.0.2-1.20.1.jar
 AllStackable-v2.0.0-1.20.1.jar
 alternate-current-mc1.20-1.7.0.jar
 architectury-9.1.12-fabric.jar
 areas-1.20.1-5.3.jar
 balm-fabric-1.20.1-7.2.1.jar
 betterbeds-1.3.0-1.19.3.jar
 chesttracker-1.20.1-1.1.23.jar
 CITResewn-1.1.3+1.20.jar
 cloth-config-11.1.118-fabric.jar
 Clumps-fabric-1.20.1-12.0.0.3.jar
 collective-1.20.1-7.30.jar
 continuity-3.0.0-beta.4+1.20.1.jar
 CreativeCore_FABRIC_v2.11.16_mc1.20.1.jar
 dashloader-5.0.0-beta.2+1.20.0.jar
 Debugify-1.20.1+2.0.jar
 DetailArmorBar-2.6.3+1.20.1-fabric.jar
 Display Case-fabric-1.20-1.0.7.jar
 DistantFriends-fabric-1.20.1-0.5.4.jar
 EasyMagic-v8.0.1-1.20.1-Fabric.jar
 EasyShulkerBoxes-v8.0.1-1.20.1-Fabric.jar
 emi-1.1.1+1.20.1+fabric.jar
 EnchantingInfuser-v8.0.2-1.20.1-Fabric.jar
 enhancedblockentities-0.9+1.20.jar
 entityculling-fabric-1.6.2-mc1.20.1.jar
 essential_1-3-0-2_fabric_1-20-1.jar
 fabric-api-0.91.1+1.20.1.jar
 fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
 fallingleaves-1.15.2+1.20.1.jar
 ferritecore-6.0.1-fabric.jar
 ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
 ImmediatelyFast-Fabric-1.2.10+1.20.4.jar
 immersive_paintings-0.6.7+1.20.1-fabric.jar
 indium-1.0.30+mc1.20.4.jar
 interactic-0.2.0+1.20.jar
 InvMove-1.20-0.8.4-Fabric.jar
 krypton-0.2.3.jar
 lazydfu-0.1.3.jar
 litematica-fabric-1.20.1-0.15.3.jar
 lithium-fabric-mc1.20.1-0.11.2.jar
 lootr-1.20-0.7.29.75.jar
 malilib-fabric-1.20.1-0.16.3.jar
 mcpitanlibarch-1.9.4-1.20.1-fabric.jar
 midnightcontrols-1.8.2+1.20.jar
 modernfix-fabric-5.13.0+mc1.20.1.jar
 modmenu-7.2.2.jar
 moonlight-1.20-2.9.13-fabric.jar
 MoreChestVariants-1.5.0-beta.3+1.20.2-Fabric.jar
 MoreCraftingTables-1.2.0+1.20.2-Fabric.jar
 notenoughanimations-fabric-1.6.4-mc1.20.jar
 owo-lib-0.11.1+1.20.jar
 paladin-furniture-mod-1.2.0-fabric-mc1.20.1.jar
 Patchouli-1.20.1-84-FABRIC.jar
 PuzzlesLib-v8.1.16-1.20.1-Fabric.jar
 Quad-1.1.0+1.20.4-Fabric.jar
 sandwichable-1.3.1+1.20.1.jar
 seamless-loading-screen-2.0.3+1.20.1-fabric.jar
 simplyswords-fabric-1.53.0-1.20.1.jar
 smoothswapping-0.9.3.1-1.20.2-fabric.jar
 sodium-fabric-0.5.8+mc1.20.1.jar
 spark-1.10.53-fabric.jar
 starlight-1.1.2+fabric.dbc156f.jar
 supplementaries-1.20-2.7.35-fabric.jar
 syncmatica-1.20.1-0.3.11.jar
 toms_storage_fabric-1.20-1.6.4.jar
 travelers-backpack-1.20.1-9.1.9.jar
 UncraftingTable-fabric-1.2.9.jar
 UniversalEnchants-v8.0.0-1.20.1-Fabric.jar
 VisualWorkbench-v8.0.0-1.20.1-Fabric.jar
 waystones-fabric-1.20-14.1.3.jar
 Xaeros_Minimap_23.9.7_Fabric_1.20.jar
 XaerosWorldMap_1.37.8_Fabric_1.20.jar
 yet-another-config-lib-fabric-3.2.2+1.20.jar
 YungsApi-1.20-Fabric-4.0.3.jar

 - Version 1.9.3 - 1.20.1
 
I reverted back to 1.8.2 and the also went back a version on EMI too when it was working and the same problem happens.

**Comment by Motschen** [comment]
Fixed in 1.9.4 :)
