### ISSUE TITLE
Can't break blocks in Survival mode in 1.20.4

### ISSUE THREAD

**Issue by Gamerbiomek2** [TeamMidnightDust/MidnightControls#264]
Can't break blocks in Survival mode

**Comment by Motschen** [comment]
Are you using MidnightControls 1.9.4? I fixed this exact bug in this version.

**Comment by Gamerbiomek2** [comment]
I didn't see there was an updated version, all I saw was 1.9.3 lol
downloading the new update now

**Comment by Gamerbiomek2** [comment]
it works now
