### ISSUE TITLE
Bug: can't exit pause menu when window is unfocused

### ISSUE THREAD

**Issue by IceYetiWins** [TeamMidnightDust/MidnightControls#276]
When unfocused input is enabled, when I click the mouse outside the window, it automatically goes to the pause screen and cannot be exited by the controller (by pressing b or hitting a on return to game). The menu works fine when the window is in focus. The controller still works when unfocused but can't go out of the menu.

The game and all mods are on the latest versions (mc 1.20.4, fabric loader 0.15.10, fabric api 0.97.0, midnight lib 1.5.3, midnight controls 1.9.4). I am on Linux Manjaro if that makes a difference.

**Comment by Androser420** [comment]
have u tried doing F3 + P ingame?

**Comment by IceYetiWins** [comment]
Didn't know that was a thing but it worked, thanks so much! Feel like maybe that should be enabled by default when unfocused input is enabled.
