### ISSUE TITLE
MidnightControls crashes on 1.19.

### ISSUE THREAD

**Issue by Kichura** [TeamMidnightDust/MidnightControls#28]
**Describe the bug**
When attempting to open up midnightcontrols in 1.19, the client will just refuse to run at all due to certain mixins not being supported.

**To Reproduce**
1. Get the latest midnightcontrols mod,
2. Ensure the client version is on 1.19 instead,
3. Start up the game,
4. Expect a crash to happen.

**Expected behavior**
The client would continue to run properly despite of unforeseen consequences.

**Screenshots**
(Unavailable to provide any)

**Desktop (please complete the following information):**
 - OS: Linux
 - Minecraft: 1.19
 - Fabric: 0.55.1+1.19
 - Mods: Only the API and MidnightControls
 - Version: 1.0.0+1.18
 - Branch: 1.18

**Additional context**
Assuming this is a bit of an annoyance but getting this checked upon wouldn't hurt - and also making this issue so that others don't have to dupe it.

**Comment by Motschen** [comment]
I just opened a PR to update SpruceUI to 1.19, as MidnightControls relies on that

**Comment by Kichura** [comment]
> I just opened a PR to update SpruceUI to 1.19, as MidnightControls relies on that

will look forward into that.

**Comment by Motschen** [comment]
MidnightControls 1.1.0 is now out with support for 1.19 :)
