### ISSUE TITLE
1.21 support 

### ISSUE THREAD

**Issue by RoberbufDx8105** [TeamMidnightDust/MidnightControls#285]
**Is your feature request related to a problem? Please describe.**
So I wanted to play Minecraft Java 1.21 with my friends on the same PC. So far I got multiple instances with their own Microsoft account and a server, but I need controller support.

**Describe the solution you'd like**
I would like to have a 1.21 version of Midnight Controls.

**Describe alternatives you've considered**
Using the Controlify mod. It has 1.21 support but there are two main issues:
•Right stick doesn't work when window is out of focus.
•Only language supported right now is English.

**Additional context**
I think that TeamMidnightDust is already working on it and this is just a reminder.

**Comment by OConnorsRule** [comment]
agreed, we need 1.21 support

**Comment by RoberbufDx8105** [comment]
Thanks!
