### ISSUE TITLE
"Incompatible mod set" attempting to use with 1.19

### ISSUE THREAD

**Issue by ShimmerFairy** [TeamMidnightDust/MidnightControls#30]
**Describe the bug**
After downloading MidnightControls (and the listed dependency on modrinth, MidnightLib), attempting to start the game fails with

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.36.0 or later.
	 - Replace mod 'SpruceUI' (spruceui) 4.0.0+1.19 with version 3.2.0 or later that is compatible with:
		 - Other constraints that can't be automatically determined
Unmet dependency listing:
	 - Mod 'MidnightControls' (midnightcontrols) 1.1.0+1.19 requires version 0.36.0 or later of fabric, which is missing!
	 - Mod 'MidnightControls' (midnightcontrols) 1.1.0+1.19 requires version 3.2.0 or later of mod 'SpruceUI' (spruceui), which can't be loaded due to other constraints!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I have tried finding SpruceUI on modrinth, but it's missing, and I don't know where to look for it. (It's not listed as a dependency on the website either.) I also installed fabric just the other day, so I'd be surprised if it was really out of date.

**To Reproduce**
1. Go to https://modrinth.com/mod/midnightcontrols/version/1.1.0 and download it.
2. Click through to the listed dependencies (just the one) and download the latest versions of them as well.

**Expected behavior**
For Minecraft to properly load and function as normal.

**Desktop (please complete the following information):**
 - OS: Linux
 - Minecraft 1.19
 - Fabric fabric-loader-0.14.6-1.19
 - Mods Iris 1.2.5, MidnightControls 1.1.0, MidnightLib 0.5.2, Sodium 0.4.2build16
 - Version 1.1.0

**Comment by Motschen** [comment]
It looks like you're missing Fabric API, which is required for basically every fabric mod.
SpruceUI is already included in the mod though.
