### ISSUE TITLE
Bug: Interfaces crash from time to time.

### ISSUE THREAD

**Issue by seriousfreezing** [TeamMidnightDust/MidnightControls#305]
**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Minecraft 1.21.1
 - Modloader Fabric 0.16.4
 - Fabric-api-0.103.0+1.21.1
 - Mods Modpack [I'll send if need]
 - Version 1.10.0

**Additional context**
[crash-2024-09-05_22.22.44-client.txt](https://github.com/user-attachments/files/16901670/crash-2024-09-05_22.22.44-client.txt)
https://paste.atlauncher.com/view/7cfee9ea-42ff-4e16-8a85-dd68ae076289

**Comment by Motschen** [comment]
This is probably caused by FancyMenu.
I'll release an update to address this (and other issues) soon.
