### ISSUE TITLE
View input jitter when under 60 FPS

### ISSUE THREAD

**Issue by Wolf-64** [TeamMidnightDust/MidnightControls#31]
Love your effort to bring controller input back to MC Java! Works almost flawlessly on Steam Deck, too!

On the Steam Deck I always limit the FPS to 30 for longer battery life. Unfortunately, the view input (right analog stick) with this mod is very jittery and not smooth at all at 30 FPS. It’s barely noticeable at 60 FPS. It feels like it’s making little jumps instead of a smooth curve. Also the hand model is jittering a lot, which I think is indicative of the jittery input.

Settings are default, both in Minecraft and Steam Deck’s default gamepad layout.

MidnightControls 1.2.1

 - OS: SteamOS 3.2
 - Minecraft 1.19
 - Fabric 0.14.7
 - FabricAPI 0.56.3, Sodium 0.4.2

**Comment by AustinHasten** [comment]
Same here on Windows.

**Comment by Wolf-64** [comment]
I would like to re-open this issue, as with version 1.2.1 of MidnightControls there was no noticeable change in the above described behaviour of view input.

**Comment by Motschen** [comment]
The latest update noticably improved the camera in my testing, but I'll look into this further.

**Comment by Motschen** [comment]
Closing this in favor of #38
