### ISSUE TITLE
Bug: The game gets stuck on a black screen

### ISSUE THREAD

**Issue by stantios** [TeamMidnightDust/MidnightControls#310]
**Describe the bug**
The game gets stuck on a black screen when launching the game.

**To Reproduce**
1. Use MidnightControls v1.10.0-beta.1
2. Launch the game.
3. Wait for the game window to open.
4. You will find that you are stuck on a black screen.

**Expected behavior**
I would expect the game to keep loading and put me into the main menu.

**Screenshots**
![88009](https://github.com/user-attachments/assets/b114f8e8-251f-4718-adee-5163eac00a63)

**Desktop (please complete the following information):**
 - OS: macOS
 - Minecraft: 1.20.1
 - Modloader: Fabric Loader 0.16.7
 - Fabric/Quilt Libraries: Fabric API 0.105.0+1.21.1
 - Mods: Fabric API 0.105.0+1.21.1, MidnightControls v1.10.0-beta.1
 - Version: 1.10.0-beta.1

**Additional context**
This could a macOS only issue, but I'm not fully sure.

Here are my logs: <https://mclo.gs/5dghQrF>

**Comment by Motschen** [comment]
Could you test if this also happens on older versions of the mod?

**Comment by stantios** [comment]
This issue is not present with MidnightControls 1.9.4.

**Comment by Motschen** [comment]
This might be caused by the bundled version of MidnightLib.
Try installing MidnightLib 1.6.3 alongside it.

**Comment by stantios** [comment]
It seems that MidnightControls 1.10.0-rc.2 fixes this issue, and the black screen no longer appears. I didn't need to install MidnightLib 1.6.3 to fix this issue.

**Comment by Motschen** [comment]
Yes, I updated the bundled MidnightLib version in rc2 :)
