### ISSUE TITLE
Mod Support: Legacy4j

### ISSUE THREAD

**Issue by jakeyhanna** [TeamMidnightDust/MidnightControls#320]
**Is your compatibility request related to a problem? Please describe.**
Midnight controls work mostly pretty good without any flaws using the legacy4j mod (specifically the RE-console modpack), Although there is one problem i encountered with it and that is scrolling through The crafting menu/Most menus the mod provides.

You might be asking why would i use midnight control over the mod's native controller support because me and my cousin play splitscreen and want to experience legacy minecraft again, But the native controller support doesn't support unfocused input and 2 controllers connected at the same time

**Describe the way of compatibility you'd imagine**
I would like to be able to switch between the tabs in the menu using RB LB RT LT like the way the native controller support does moving through the crafting tabs by using these buttons

**Describe alternatives you've considered**
I wanted to try controllify but Every version crashes with the re-console Modpack/legacy4j with only midnight controls working, Although the menu support is jarring with us using the virtual mouse

**Comment by Androser420** [comment]
you actually can do that in newer legacy4j versions when enabling this option in Game Options
![image](https://github.com/user-attachments/assets/8db6d54d-71f5-40eb-9ed3-b0ce193bdf2f)

btw u should probably use SDL3 controller handler in the controller settings as well

**Comment by jakeyhanna** [comment]
> you actually can do that in newer legacy4j versions when enabling this option in Game Options ![image](https://private-user-images.githubusercontent.com/72580260/392588064-8db6d54d-71f5-40eb-9ed3-b0ce193bdf2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTUwOTcsIm5iZiI6MTczNDU1NDc5NywicGF0aCI6Ii83MjU4MDI2MC8zOTI1ODgwNjQtOGRiNmQ1NGQtNzFmNS00MGViLTllZDMtYjBjZTE5M2JkZjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDIwNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjdmNTRmMzk1MWUzMDI3OTk2MjZjOWRjMGNlYWQwZmI5NGE2NWFmMTc1ZjliYjYzZTg1NjlkMTNmNjM3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gXgz7JQZR3W5yyPaVNJh6VosP_dyfsAfe238SSwB_1c)
> 
> btw u should probably use SDL3 controller handler in the controller settings as well

Ah Thank you!!, That seemed to have fixed my problem, Although i will keep using the GLFW controller handler because SDL3 breaks after connecting 2 controller to the same system which makes me restart the game as a whole

Again thank you!
