### ISSUE TITLE
mod conflict , Game Crash When Start

### ISSUE THREAD

**Issue by ShulkerSakura** [TeamMidnightDust/MidnightControls#34]
ScreenShot:
"Sorry,this problem does not arise 100% of the time,So I can't provide you screenshots but when the problem happened , the game start and stuck on white screen before Mojang Logo and for a long time then game crashed,It is both happened under Linux & Windows,So it may not the problem of my system"
 - OS: Both under Debian Linux & Windows10/11
 - Minecraft 1.19
 - Fabric 0.14.7
 - Mods 3DSkinLayer-1.4.7 Fabric-API-0.55.2 InventoryProfilesNext-1.5.0 Lithium-0.8.0 mcwifipnp-1.5.5 modmenu-4.0.0 notenoughanimations-1.6.0 sodium-0.4.2 wavecapes-1.2.0 [midnightcontrols-1.1.0] iris-1.2.5-pbr-beta
 - Version 1.1.0
 - Branch main

**Comment by Motschen** [comment]
Could you provide me with the crash log, please?

**Comment by ShulkerSakura** [comment]
I will try to catch a crash log.

**Comment by ShulkerSakura** [comment]
> 请给我崩溃日志好吗？

It's weird that after I opened this issue the crash never happen again, but it just need a really long long long long time to start up the game. Can you try the same mods that I use?

**Comment by Motschen** [comment]
I've used all of these mods in conjunction with MidnightControls and I haven't encountered this issue.

**Comment by Motschen** [comment]
Feel free to reopen if you can send the log.
