### ISSUE TITLE
[bug] Turning is way too fast, sharp, and choppy

### ISSUE THREAD

**Issue by Merith-TK** [TeamMidnightDust/MidnightControls#38]
**Describe the bug**
Turning is way too fast, sharp, and choppy

**To Reproduce**
1. Try to turn in game using joystick

**Expected behavior**
Turning would work relatively like it does on console

**Desktop (please complete the following information):**
 - OS: N/A (windows, linux, SteamOS, etc)
 - Minecraft: 1.19
 - Version: 1.1.0
 
**Additional context**
its been an issue since LambdaControls and pretty much, litterally, the only thing holding me back from consistently using this mod. just looking around actually starts to give me an headache

Everything else about this mod is perfect,

**Comment by ghost** [comment]
I'm using a Steam Deck, and noticed the same problem. Resolved mostly by setting the game to run at 60FPS instead of 30 or 40. I know it's not a fix but it is a workaround.

**Comment by Merith-TK** [comment]
I turned my look sensitivity down to the 14-16 range that helped, but it still feels too sharp, will try what you suggested

**Comment by Motschen** [comment]
I tried to improve it in v1.3.0
Let me know if it's gotten any better

**Comment by Merith-TK** [comment]
That does help smooth it out, but yeah, the default rotation speed is *way too high* for most controllers I have used since lambda, PS3, Xbox One, Xbox 360 (3rd party wired), ps4, deck, etc, 

but yeah, latest release does noticeably improve it

**Comment by Merith-TK** [comment]
also found crashing bug

**Comment by ckosmic** [comment]
To fix choppiness on Steam Deck you can set the rotation speed to 0 in the MidnightControls settings and bind the joystick to Joystick Mouse in Steam Input.

**Comment by ComoSgt** [comment]
Hello! I made a controller config via Steam that hopefully helps with this issue kind of based on the comment above. I modeled the Joystick Mouse settings after the default deadzones and max zones in the mod and I chose a sensitivity that worked for me. If you read the description of the config it'll say what you can do to get some Bedrock control scheme parity.

steam://controllerconfig/minecraft/2850829815

**Comment by Motschen** [comment]
I think I finally managed to fix it, will be coming in 1.6.0

**Comment by Motschen** [comment]
1.6.0 will release sometime this week, in the meantime, please test the pre-release [midnightcontrols-1.6.0-pre1+1.19.zip](https://github.com/TeamMidnightDust/MidnightControls/files/9595080/midnightcontrols-1.6.0-pre1%2B1.19.zip) (you can also compile it yourself if you want) and give me some feedback, especially on the camera changes.

**Comment by guighub** [comment]
I'm having this exact issue on 1.90+1.20.2 on my Steam Deck. I've messed with all of the controls and video settings and nothing has solved it so far.

**Comment by Merith-TK** [comment]
> I'm having this exact issue on 1.90+1.20.2 on my Steam Deck. I've messed with all of the controls and video settings and nothing has solved it so far.

I have just decided to use [Controlify](https://modrinth.com/mod/controlify) which uses native libraries for controller support (this includes explicit steamdeck support)
