### ISSUE TITLE
[bug] Creative Mode flight is excessively slow

### ISSUE THREAD

**Issue by Merith-TK** [TeamMidnightDust/MidnightControls#39]
**Describe the bug**
when flying in creative mode (with default settings), you move at about the speed in which you sneak walk, 

**To Reproduce**
1) open creative world
2) fly in creative, 
3) try to move

**Expected behavior**
movement speed to be reasonable

**Desktop (please complete the following information):**
 - OS: Windows, Linux (SteamOS)
https://mclo.gs/QhZvgbg
logs contain everything else (ignore repeating line i know whats causing that)

**Comment by Motschen** [comment]
Disable the enhanced flight option in Bedrockify

**Comment by Merith-TK** [comment]
its called "Flight Momentum" in bedrockify, but yes that fixed it!
