### ISSUE TITLE
Xbox Series Controller diagonal input slow on left stick

### ISSUE THREAD

**Issue by sjk210** [TeamMidnightDust/MidnightControls#42]
While using the Xbox Series Controller plugged in using USB (Don't know if that changes anything), moving diagonally on the left stick is slow. Going forward, backwards, and sideways all are fine, but if i try to go diagonal then I slow down and it ends up stopping my sprint. 

1. Plug in Xbox Series Controller
2. Go into game
3. Move diagonally with the left stick
4. You move slow

What I expect to happen is that the speed of moving diagonally is the same as moving forward or backwards. 

https://drive.google.com/file/d/1HTyk0SgirxFRk4miaFWyb1bTCJLqhpoO/view?usp=sharing
This is a video of what I am talking about, file size was too big for github

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.19
 - Fabric 0.14.7-1.19
 - Mods: fabric-api-0.55.3, sodium-fabric-mc1.19-0.4.2, reeses_sodium_options-1.4.3, sodium-extra-0.4.5, lithium-fabric-mc0.8.0, phosphor-fabric-mc0.8.1, CustomPlayerModels-Fabric-0.4.3a, midnightcontrols-1.2.1, midnightlib-0.5.2
 - Version: 1.2.1
 - Branch: Release

**Comment by skunkmommy** [comment]
This sounds like a controller issue, my DS4's stick drifts quite heavily and sometimes does a thing similar to what you're describing. Have you tried with several different Series controllers to see if it's consistent?

**Comment by sjk210** [comment]
> 

While I do not have another series controller, I do have an old Xbox One S controller. Same issue occurs there for me. Also tried using a switch pro controller, and once again same issue applies. Another thing is that when using my Series controller on other games, or on my xbox, the issue doesn't happen at all, and using https://gamepad-tester.com/ I do not see any problems with my joystick.

**Comment by TheCongressman** [comment]
This is not a controller issue, I have the same problem on a DS4 controller as well as a Switch Pro controller. This is only an issue when in analog movement mode. I suspect this is because the mod has a square analog gate instead of a circle.

**Comment by TheCongressman** [comment]
This is not a controller issue, I have the same problem on a DS4 controller as well as a Switch Pro controller. This is only an issue when in analog movement mode. As well, when sprinting, a diagonal tilt will cause the sprint to stop.

**Comment by dogtopus** [comment]
FYI this should be fixed in cdafde0.

> a diagonal tilt will cause the sprint to stop.

I noticed this too, even after the slowdown issue is fixed. Although it became intermittent and will work most of the time. I think it might be better to reduce the sprint speed threshold a bit so a non-perfect full push will not drop sprint.
