### ISSUE TITLE
Request: Separate Vertical and Horizontal Rotation Speeds

### ISSUE THREAD

**Issue by ronniedude** [TeamMidnightDust/MidnightControls#43]
If you try using Minecraft Bedrock Edition with a supported controller there are menu options to reduce the vertical (up & down) camera tilt speed as a separate value. This is useful because many players including myself find having fast horizontal (left & right) camera pan speed useful during gameplay, while a slower, finer control with the vertical axis feels more natural.

**Comment by Motschen** [comment]
Couldn't you just change the right Y- and X-axis maximum values in Controler Options to achieve this effect?

**Comment by ronniedude** [comment]
@Motschen I found that method was limiting and confusing to setup. Determined, I have code changes in my PR. If you have the ability to do so please review and let me know what you think.

**Comment by Motschen** [comment]
Added in 1.3.0
