### ISSUE TITLE
Can't Use mouse properly on 1.19

### ISSUE THREAD

**Issue by EightBitPlayz** [TeamMidnightDust/MidnightControls#45]
When I click my left mouse button to attack/destroy I won't resister and it will act as if I did not press the button so I can not break blocks I tried to see if my config was wrong and my attack/ destroy key was set to the left mouse click does not happen when not using the mod.
 - OS: [Windows 11]
 - Minecraft [1.19]
 - Fabric [0.14.8]

**Comment by Motschen** [comment]
Does this also happen with MidnightControls 1.1.0?

**Comment by Motschen** [comment]
I think I know the cause, I bound a keybind to the mouse for testing and forgot to remove it, I'll fix it when I'm back home, try to use 1.2.0 in the mean time.

**Comment by Zorklis** [comment]
Could this have broken my quick crafting and quick trading, I can drag drop craft/trade but not quick mode

**Comment by Motschen** [comment]
Does this still happen on the latest version for you?

**Comment by Zorklis** [comment]
> 
At first it seemed to have fixed it but after restart I think broke it again,  it could have one of two other mods but I highly doubt it

**Comment by Motschen** [comment]
Try using MidnightControls without the other mods

**Comment by Zorklis** [comment]
I removed the entire Mod folder (like yesterday) and it still didn't fix it. I tried a new world yesterday and that didn't fix it either. I'll try to do some other testing I suppose

**Comment by Zorklis** [comment]
Okay, fresh install, new world and quick crafting worked. then mods without MidnightControls and it broke, strangely other suspected mods were also excluded
