### ISSUE TITLE
Pick up stack not working smoothly in 1.19 - XInput Logitech F310

### ISSUE THREAD

**Issue by andrewaramsay** [TeamMidnightDust/MidnightControls#50]
**Describe the bug**
When opening the inventory and trying to pick up an item (or stack) with the A button, it seems to pick it up and immediately drop the item.  If you hold A for 1-2 seconds it will pick up properly, then afterward it seems to work fine with typical button press duration.  If the inventory is closed and opened again, it is back in the bugged state until another long-press.  I've only recently added this mod to our 1.18.2 setup, but I'm pretty sure it wasn't doing this before the upgrade to 1.19

**To Reproduce**
1. Open inventory
2. Press A on any item

**Expected behavior**
The item or stack is picked up.

**Actual behavior**
The item is not picked up, if it was the active item on the hotbar, you can see it flash in the character's hand like it was picked up and set back down.

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.19
 - Fabric 0.14.8
 - Mods:
 -- automated-craftnig 1.4.6+MC1.19
 -- balm-fabric 4.3.0
 -- cloth-config 7.0.72
 -- fabric-api 0.56.3+1.19
 -- journeymap 1.19-5.8.frc1-fabric
 -- lithium-fabric mc1.19-0.8.0
 -- midnightcontrols 1.2.2+1.19
 -- phosphor-fabric mc1.19.x-0.8.1
 -- sodium-fabric mc1.19-0.4.2+build.16
 -- waystones-fabric-1.19-11.0.1
 -- worldedit 7.2.11-beta-01
 - Version 1.2.2+1.19
 

**Additional context**
We are running two instances of Minecraft on the same computer, one with midnight controls, virtual mouse, unfocused input.  The other without midnight controls at all, using keyboard and mouse.  This is happening in a LAN game and the keyboard/mouse setup is the host.  The controller being used is a logitech F310, it seems to exhibit this same behavior in both XInput and Direct Input modes. 

This bug didn't appear to be present in my initial testing on 1.18.2, but there were some other variables when it was working: we were testing in single player, only one instance of minecraft was running, all of the above mods were on their latest 1.18.2 versions

**Comment by andrewaramsay** [comment]
I just tried eliminating a few variables.  The behavior is the same in single player, single instance of minecraft running, with only the following two mods:
-- fabric-api 0.56.3+1.19
-- midnightcontrols 1.2.2+1.19

**Comment by Motschen** [comment]
I think I know the cause, I'll fix it in the next update.
Thanks for informing me about it.
