### ISSUE TITLE
Stack pickup in inventory doesn't work on the Steam Deck

### ISSUE THREAD

**Issue by Donnnno** [TeamMidnightDust/MidnightControls#57]
**Describe the bug**
Hi, thanks for this fantastic mod that allows me to play Minecraft on the go! 

I've one issue tho, the "a" button, assigned to the pickup stack doesn't work in the inventory, on the steam Deck.

**To Reproduce**
1. Open inventory with the Deck controls
2. Click on 'A'
3. Nothing is picked up

**Desktop (please complete the following information):**
 - OS: Linux (Deck version)
 - Minecraft 1.19
 - Fabric 0.14.8
 - Mods Fabric API, FallingTree, Iris, LambDynamicLights, Mod Menu, Sodium, Xaero's Minimap
 - Version 1.3.0+1.19

**Additional context**

**Comment by Motschen** [comment]
Which game mode are you in? Creative and Survival inventories are handled seperately, so it's vital information for me.

**Comment by Donnnno** [comment]
Hey! I'm playing in survival mode right now :)

**Comment by Motschen** [comment]
It worked really well in my testing and playing, so idk what's going on here.

**Comment by Donnnno** [comment]
Strange, I'll take a more in-depth look too then!

**Comment by Motschen** [comment]
Could you try if it also happens using MidnightControls 1.0.0 on 1.18 and 1.1.0 on 1.19?
This might help me isolate if it's caused by a regression in later versions

**Comment by Donnnno** [comment]
Just tested both versions, and it does seem to work with 1.0.0 on 1.18, but not 1.1.0 on 1.19

**Comment by Motschen** [comment]
Thanks, that should help me figure it out.

**Comment by Motschen** [comment]
Could you try if this version fixes it?
https://workupload.com/file/ULTj59jCLgd

**Comment by Donnnno** [comment]
Yesss, it works now!

Thank you ! :)

**Comment by Motschen** [comment]
Great!
