### ISSUE TITLE
Azeron Keypad not able to map buttons (even in Xbox emulation)

### ISSUE THREAD

**Issue by johnsturgeon** [TeamMidnightDust/MidnightControls#58]
**Describe the bug**
I have an Azeron Keypad that I use to play minecraft, and I'd like to use the 'joystick' for analog movement.

When it's plugged in, it *is* recognized as a controller, but for some reason, it won't let me change the key bindings in the UI.  Only my Xbox Controller can update key bindings.

**Additional context**
Screenshot of Azeron (recognized)
<img width="690" alt="image" src="https://user-images.githubusercontent.com/9746310/177019043-1b02a1c0-5aa1-4ca5-8e1a-c6b661322165.png">
Screenshot of unresponsive button binding
<img width="696" alt="image" src="https://user-images.githubusercontent.com/9746310/177019048-57812d8c-f157-4ff0-9480-6461c519632d.png">

**Comment by Motschen** [comment]
The orange text indicates missing mappings, try creating one using gamepad-tool (https://generalarcade.com/gamepadtool/) and paste it into the Custom Mappings section.
If that works, you might as well want to contribute the mapping to https://github.com/gabomdq/SDL_GameControllerDB so other people using the same Controller don't have to do that themselves.
