### ISSUE TITLE
Mods shortcurts

### ISSUE THREAD

**Issue by Hapcky** [TeamMidnightDust/MidnightControls#6]
I don't know if it's intentional or not but the option to add buttons for zoom, backslot addon or for some backpack mod doesn't appear, great mod saved me

sorry for the english mistakes i'm brazilian

**Comment by Felix14-v2** [comment]
Maybe you should try to suggest this feature to [Amecs](https://github.com/Siphalor/amecs)? It focuses on  expanding the capabilities of keybinds, and it would be more logical to implement this feature on Amecs's part.

**Comment by RaptaG** [comment]
Yes please

**Comment by Motschen** [comment]
Added in v1.2.0
Have fun!
