### ISSUE TITLE
Would you please port the Crawl button overlap fix to 1.18.2? TYVM

### ISSUE THREAD

**Issue by ardissaps** [TeamMidnightDust/MidnightControls#61]
Would you please port the Crawl button overlap fix to 1.18.2? TYVM

**Comment by Motschen** [comment]
I'll release a backport of the entirety of 1.4.0 when I'm back from school later today, you can already get it by compiling the 1.18 branch

**Comment by Motschen** [comment]
Or download this build I uploaded yesterday to my Discord server: https://cdn.discordapp.com/attachments/642070954096459777/993971414526865468/midnightcontrols-1.4.0-1.18.jar

**Comment by ardissaps** [comment]
No hurry. I can wait (installing mod with launcher).

**Comment by ardissaps** [comment]
Thank you very much for the [port](https://github.com/TeamMidnightDust/MidnightControls/releases/tag/v1.4.1)! :)
