### ISSUE TITLE
[bug] Switch pro controller not being detected properly

### ISSUE THREAD

**Issue by drakosoldier298** [TeamMidnightDust/MidnightControls#65]
**Describe the bug**
Switch pro controller connecting as gamepad and doing nothing. 

**Expected behavior**
Switch pro controller to connect as a switch controller and be able to move around and play.,
**Desktop (please complete the following information):**
 - OS: windows 11
 - Minecraft 1.19
 - Fabric fabric 0.14.8
 - Mods https://gitlab.com/drakosoldier298/vanillia-modpack/-/tree/1.19
 - Version 1.4.0
 - Branch unknown, release I presume

**Comment by Motschen** [comment]
Does the controller name appear orange in the Controller Options? If so, try creating a custom mapping.
