### ISSUE TITLE
Real Mouse Does Not Disappear When Using the Virtual Mouse

### ISSUE THREAD

**Issue by FireController1847** [TeamMidnightDust/MidnightControls#66]
**Describe the bug**
When in "Controller" mode with the "Virtual Mouse" enabled, when entering gameplay mode, your real mouse does not disappear.

**To Reproduce**
1. Enable controller mode
2. Enable virtual mouse
3. Go into first person (regular gameplay) and use a controller to move
4. Notice how you have to manually move your real mouse off screen for it to be away

**Expected behavior**
I expected the mouse to disappear when in first-person (regular gameplay) mode.

**Screenshots**
https://user-images.githubusercontent.com/16494272/178082770-ad0676ce-4e78-459b-b197-c355d73f5d5f.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft: 1.19
 - Fabric: 0.14.8
 - Mods: Alot, ask directly if you want the full list, but this still occurs without them
 - Version: 1.4.0+1.19
 - Branch: Release

**Additional context**
N/A

**Comment by Motschen** [comment]
This is actually intended behavior of the virtual mouse, as this allows for playing Minecraft in split screen.

**Comment by FireController1847** [comment]
Would it be possible to convert this into a feature request and request an option for this functionality?

**Comment by Motschen** [comment]
What functionality? If the mouse was hidden, the virtual mouse would be pointless.
