### ISSUE TITLE
Question about new icons tip.

### ISSUE THREAD

**Issue by Ivanoshechka** [TeamMidnightDust/MidnightControls#69]
I wanna draw the icon's from Legacy (Console) minecraft. But, is it needed at all?
![image](https://user-images.githubusercontent.com/88715280/178532333-0b2a2e91-07ee-4988-ac77-21c3f9cd1485.png)
Answer please.

**Comment by Ivanoshechka** [comment]
69 pog.

**Comment by Motschen** [comment]
Yeah, sure, I can ship them in an optional included resourcepack.
