### ISSUE TITLE
I redraw bedrock icon to 15x15 pixel.

### ISSUE THREAD

**Issue by Ivanoshechka** [TeamMidnightDust/MidnightControls#7]
Yeah, i think, the bedrock players gonna be happy.

So, i don't redraw the main buttons & share and setting button. I left it as is for myself. (Because of this, I did not turn to Lambd. When I wanted to, it was too late.)
![image](https://user-images.githubusercontent.com/88715280/163827915-403b4fb6-3761-414b-b007-34aeb9e6ff43.png)

If you need a middle, it seems that 13x13 will be small.. So.. I don't know.
There screenshot's:
![2022-04-18_21 06 09](https://user-images.githubusercontent.com/88715280/163829163-f6256276-0d48-4450-952c-2f5f23c36e21.png)
![2022-04-18_21 10 01](https://user-images.githubusercontent.com/88715280/163829198-6f982951-0998-41f9-9226-d4dc11bb1ba9.png)
![2022-04-18_21 09 39](https://user-images.githubusercontent.com/88715280/163829185-0908a04c-a7a2-4f6f-8802-46e6e438a8ba.png)
![2022-04-18_21 09 50](https://user-images.githubusercontent.com/88715280/163829190-58836942-279e-4aed-b0b8-7149ca10707a.png)

![controller_buttons](https://user-images.githubusercontent.com/88715280/163829296-6e14f74d-4106-4b5d-b80b-13c76f05cd4d.png)
(-_Idk how to send to full resolution._-) Okay, i got it.

**Comment by Motschen** [comment]
Looks great, thank you very much :)
Gonna be added in the next beta

**Comment by Motschen** [comment]
Added in 0.2.0 :)
