### ISSUE TITLE
Steam Remote Play input not recognized

### ISSUE THREAD

**Issue by Coconut-Nivrinu-Squirt** [TeamMidnightDust/MidnightControls#72]
with a virtual steam controller the inputs do not register. linux base os. running 1.18.2, any reason for this bug?

**Comment by Motschen** [comment]
With steamplay you mean steam's remote play, right?

**Comment by Coconut-Nivrinu-Squirt** [comment]
Yes, with a virtual controller that is from the connected device

________________________________________

**Comment by Coconut-Nivrinu-Squirt** [comment]
Yes

________________________________________

**Comment by Motschen** [comment]
Closing this in favor of #256
