### ISSUE TITLE
Draw new legacy icon's tip's! (But not all. Sorry. Xd)

### ISSUE THREAD

**Issue by Ivanoshechka** [TeamMidnightDust/MidnightControls#73]
Idk what to do with dualsense, steam deck, steam controller and OUYA.
I do something with dualsense, but for others I don't know
![controller_axis](https://user-images.githubusercontent.com/88715280/178739651-fdbe4759-d839-41da-b046-d947d88e6060.png)

![controller_buttons - Copy](https://user-images.githubusercontent.com/88715280/178739387-7d8067b1-22bd-49ef-a8e5-1860305e244d.png)
.

**Comment by Ivanoshechka** [comment]
Ah yes, screenshots.
General:
![2022-07-14_15 25 52](https://user-images.githubusercontent.com/88715280/178950679-434d3437-192f-4cbb-aa40-2328bf0430a5.png)
Dualshock:
![2022-07-14_15 26 15](https://user-images.githubusercontent.com/88715280/178950763-916913a1-e6be-4368-b579-3533922e2257.png)
Dualsense:
![2022-07-14_15 26 30](https://user-images.githubusercontent.com/88715280/178950811-287bfd33-a30e-42e8-b1f7-7761342c7a5e.png)
Switch:
![2022-07-14_15 26 48](https://user-images.githubusercontent.com/88715280/178950837-2a6b2eb9-d5d0-4cf2-9a02-10f84e62d98e.png)
Xbox 360:
![2022-07-14_15 26 57](https://user-images.githubusercontent.com/88715280/178950878-abae1f99-8587-4985-9a3b-a3b0fd8de281.png)
Xbox:
![2022-07-14_15 27 06](https://user-images.githubusercontent.com/88715280/178950906-fbc32109-f8be-46f7-8f4d-ab9568f3f5bc.png)

**Comment by Motschen** [comment]
Looks great! I'll try to improvise the missing icons somehow. Thanks for your contribution!

**Comment by Motschen** [comment]
Added in 1.5.0 :)
