### ISSUE TITLE
Fix the 1px on "Y" in xbox and not only legacy icon's.

### ISSUE THREAD

**Issue by Ivanoshechka** [TeamMidnightDust/MidnightControls#84]
![image](https://user-images.githubusercontent.com/88715280/184051762-968e3d0a-2fe8-43d0-b8b9-a59b8112c031.png)
__

![controller_buttons](https://user-images.githubusercontent.com/88715280/182649405-61521761-2d5c-4700-9f13-773f0ac9d9be.png)
)

Sorry, my bad.

**Comment by skunkmommy** [comment]
Clarify - what's the issue? Is it this? If so, you should have made that clear.
![image](https://user-images.githubusercontent.com/87132635/183881765-7aedab25-eccf-4bff-85f5-6ea87db04720.png)

**Comment by Ivanoshechka** [comment]
> 
 No, i tried make it 1 in 1 to similar with xbox 360. (I use nearest neighbor method. Xd) But, but, 2 pixels would look very small compared to other buttons. 
![image](https://user-images.githubusercontent.com/88715280/184050237-89e01b19-09b9-498f-bbd1-98230694bf6b.png)

![image](https://user-images.githubusercontent.com/88715280/184049576-21d8a525-6eb7-446c-a157-10bede5cca27.png)

Issue in 1 px in "y" bottom btw.
![image](https://user-images.githubusercontent.com/88715280/184051290-eef99f8d-db6b-49e8-87d9-e162bf1bc7c2.png)
