### ISSUE TITLE
Binding of multiple keys to a single action and vice versa

### ISSUE THREAD

**Issue by CrimsonFork** [TeamMidnightDust/MidnightControls#85]
### Problem
MC doesn't let you bind multiple keys to one action, and if you bind the same key to multiple actions, only one is performed.

### Solution
I would like to have the ability for single key presses to cause multiple actions at once (e.g. `[mouse 5]` for `forward + sprint + jump` and `[mouse 4]` for `forward + sprint`) in addition to all the usual keyboard controls.

### Alternatives
For now I'm using [Amecs](https://modrinth.com/mod/amecs) and [NMUK](https://modrinth.com/mod/nmuk) for that, but I feel like the functionality would complement this mod nicely, and having to have less mods is of course always better. Also this setup currently saves one of the bindings incorrectly, and right now I can't ascertain if Midnight Controls is related to this issue.

**Comment by Motschen** [comment]
I feel like this would complicate the already quite complex code base even more and make it harder to maintain without a real benefit to most people.
Also, I don't want to steal users from Amecs and NMUK, so I won't implement this in MidnightControls.

**Comment by CrimsonFork** [comment]
Understandable, have a nice day.
