### ISSUE TITLE
Official Maven Repo?

### ISSUE THREAD

**Issue by kyrptonaught** [TeamMidnightDust/MidnightControls#86]
**Is your feature request related to a problem? Please describe.**
The readme mentions that MidnightControls has a API for developers to use, but there is no mention of how to add the mod to your project. The build.gradle does have a publishing component, but the repo is hidden behind system env variables.

**Describe the solution you'd like**
Is there an official Maven Repo used by TeamMidnightDust where this could be hosted? Or at least an official method for obtaining the project? 

**Describe alternatives you've considered**
I have tried Jitpack, but it is jank and does not succeed in building the project. In the meantime I have uploaded the project to my own repo, but an official solution would be nice.

For others with this same issue until this gets resolved, here's how you can access it from my maven:

 1. Add the repo: `maven { url = "https://maven.kyrptonaught.dev" }`
 2. Add the repos for the deps MidnightControls depends on: https://github.com/TeamMidnightDust/MidnightControls/blob/2e861470d809e7f1441a3e2df3a1e29289c59a7e/build.gradle#L62
 3. Add the dependency: `modImplementation "eu.midnightdust:midnightcontrols:1.5.0-1.19"` 
 -version 1.0.0-1.18 is also available.

**Comment by Motschen** [comment]
The official way is to use the modrinth maven and also download all required dependencies, like I did for Automobility: https://github.com/FoundationGames/Automobility/blob/1.18.2/build.gradle
I'll make sure to add it to the README when I have time.

**Comment by Motschen** [comment]
I added information on the required gradle configuration in the wiki: https://github.com/TeamMidnightDust/MidnightControls/wiki/Developers

**Comment by kyrptonaught** [comment]
The wiki does not mention the repo to find SpruceUI, it is:
	`maven { url = "https://maven.gegy.dev" }`
