### ISSUE TITLE
Mouse cursor does not hide when using virtual cursor

### ISSUE THREAD

**Issue by ghost** [TeamMidnightDust/MidnightControls#88]
**Describe the bug**
macOS's default mouse cursor is not hidden when using virtual mouse option of the mod.

**To Reproduce**
1. enable virtual mouse on mod setting

**Expected behavior**
System cursor should be hidden in game

**Screenshots**
![1](https://user-images.githubusercontent.com/96179742/183906248-be434a19-cf09-403b-93e9-370daa87e4c2.png)
![2](https://user-images.githubusercontent.com/96179742/183906275-512fff65-2192-420c-971c-ec7b2a4b56ff.png)
As you can see both virtual cursor and system cursor are visible.

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Minecraft 1.19.2
 - Fabric 0.14.9
 - Mods Irys shader
 - Version 1.5.0

**Comment by Motschen** [comment]
This is not a bug, it's an intended feature, as the virtual cursor is meant to be used to play Minecraft in split screen mode.
