### ISSUE TITLE
Inventory doesn't work when open inventory binding is the same as Back

### ISSUE THREAD

**Issue by UnderNoControl** [TeamMidnightDust/MidnightControls#93]
When you set the open inventory binding to the same button as back the inventory only opens when you hold the button and closes on release. From what I've seen Inventory activates on the button press and Back activates on button release 

Set "Inventory" to B in controller controls.
Load a world and open the inventory.

The inventory should stay open after releasing B.

 - OS: Windows 10
 - Minecraft 1.19
 - Fabric 0.14.9
 - Modpack Client Additions 1.19 https://www.curseforge.com/minecraft/modpacks/vanilla-client-side-mods-for-fabric
 - Version 1.5.0

**Comment by krazeral** [comment]
I have the same problem too
