### ISSUE TITLE
Requires a version of spruceUI mod that isnt compiled to work

### ISSUE THREAD

**Issue by EmiFree** [TeamMidnightDust/MidnightControls#99]
I ran into an issue where every time I would try to use this mod it would crash and say that spruceUI version 3.2.0 or greater was needed. I tried this with fabric mod loader 1.19.2 and with only this and fabric api in the mods folder, I also tried it with MidnightLib and that gave the same error. No where in any online tutorial or on this github did I see something saying spruceUI was a dependency. Eventually I found the github for it and the most recent compiled version on it is 1.5.2, which is too low to work. I had to compile spruceUI 4.0.0 myself to get this mod working, and now it runs fine. I seem to be the only person to ever have this issue as I could only find spruceUI ever being mentioned on its github page and almost nowhere else. I also tried this on 2 different computers. 
https://github.com/LambdAurora/SpruceUI

**Comment by Motschen** [comment]
An updated version SpruceUI is actually included in the mod already, please delete the outdated one from your mods folder.
